#!/usr/bin/env python3
"""Generate Paper 38 producer terminology records without validation claims."""

from __future__ import annotations

import csv
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "evidence"
OUT.mkdir(parents=True, exist_ok=True)

SOURCE_SHA = "ECEC3909998D3E1BD891597D2494C5A13E7E719F1B2A6CAF802515F8EEB492AC"
WITNESS_SHA = "EE420CD898E71EDE96ABADE3448ECF3CDE78ABF27A81D8381422F253FDC43E3E"
HANS_SHA = "330053BA55A857F1BA7CE43D6D8F97DE97EC3B1E350D59C21FD2F74702E8E973"
HANT_SHA = "3FD73D3BCBFDCC2B2C1C83C473092E20E60AEF633ABD85716C910DE448F1FAC8"
EVIDENCE_CLASS = "producer editorial choice in the assembled Hans target with inherited Simplified-Chinese drafting witness; independent checking absent"
HANT_STATUS = "controlled generic script derivative only; not zh-Hant-TW/HK/MO; regional lexical localization absent"
REVIEW = "independent check absent; pending"


def t(locator: str, german: str, scope: str, hans: str, hant: str, window: str,
      excluded: str, alternatives: str, basin: str, debt: str, note: str) -> dict[str, str]:
    return dict(locator=locator, german=german, scope=scope, hans=hans, hant=hant,
                window=window, excluded=excluded, alternatives=alternatives,
                basin=basin, debt=debt, note=note)


TERMS = [
    t("segment A main theorem", "normale Divisionsalgebra", "central division algebra over its center in the historical terminology", "正规除代数", "正規除代數", "A finite-dimensional division algebra whose center is the stated algebraic number field, in the paper's historical normality sense.", "a normal subgroup; an integrally closed ordinary field; a normalized algebra; any division ring without the center condition", "中心除代数; 正常除代数", "modern Sino-xenic coinage/calque", "High: 正规 has several Mainland mathematical senses and may invite modern central-simple reinterpretation; regional wording is untested.", "The producer retains the historical adjective rather than silently replacing it with 中心."),
    t("segment A main theorem and reductions", "zyklisch", "cyclic algebra or cyclic splitting-field construction", "循环", "循環", "Cyclic in the Galois/algebra sense used by Hasse's theory, including cyclic division algebras and cyclic realizability.", "periodic numerical behavior; a loop in computation; circular reasoning", "轮换; 周期; 循环型", "modern Sino-xenic coinage/calque", "Medium: 循环 is Mainland-dominant and broadly shared but its regional historical-algebra register is untested.", "Used with 域, 代数, 表示, or extension context."),
    t("segment A main theorem", "Dicksonscher Typus", "Dickson type of cyclic division algebra", "Dickson 型", "Dickson 型", "The named Dickson construction/type stated as synonymous with cyclicity in the theorem.", "a generic classification type; a personal-name translation not tied to the algebra construction", "迪克森型; Dickson 类型", "global modern loan", "Medium: Latin-script Dickson avoids transliteration choice but regional typography and name convention are untested.", "Personal name remains in Latin script."),
    t("segments A-B reductions", "überall zerfallende Algebra", "algebra split at every prime place after local extension", "处处分裂代数", "處處分裂代數", "An algebra whose extension to every completion at every prime place is split.", "an algebra that decomposes globally into arbitrary factors; an everywhere discontinuous object; polynomial splitting alone", "各处劈裂代数; 局部处处分裂代数", "modern Sino-xenic coinage/calque", "High: 处处 is concise Mandarin prose but can conceal the prime-place quantifier; regional wording and 劈裂 terminology are untested.", "The local-completion definition remains adjacent in segment A."),
    t("segment A definition", "normale einfache Algebra", "historical normal simple algebra with center equal to the base number field", "正规单代数", "正規單代數", "A simple algebra whose center is exactly the stated algebraic number field.", "a normal subgroup algebra; merely a simple algebra; a commutative field; a normalized algebra", "中心单代数; 正常单代数", "mixed/contested", "High: modern Mandarin often favors 中心单代数, while the producer preserves 正规单代数 from the historical register; regional practice is untested.", "Checker should assess historical fidelity versus modern terminology."),
    t("segment A definition of A~Omega", "Ähnlichkeit", "Brauer similarity/equivalence by associated division algebra", "相似性", "相似性", "The equivalence relation identifying matrix algebras with the same associated division algebra, not ordinary matrix conjugacy.", "matrix similarity by conjugation; geometric similarity; vague resemblance", "等价; Brauer 等价; 同类", "mixed/contested", "High: 相似性 strongly attracts ordinary matrix-similarity meaning in Mandarin; the parenthetical definition controls the intended Brauer-class sense.", "Recorded as a major sense trap for checking."),
    t("segment A local definition", "p-adische Erweiterung", "scalar extension to the p-adic completion", "p-进扩张", "p-進擴張", "The algebra obtained by extending coefficients from the number field to its completion at the prime place $p$.", "a formal power-series extension; an extension of the p-adic valuation only; a field extension unrelated to scalar extension", "p-进标量扩张; p-adic 扩张", "global modern loan", "Medium: p-进 is standard Mainland notation but regional typography and use of Latin p are untested.", "Kept paired with the named completion."),
    t("segments A-B and theorem 3", "p-Grad", "local degree at a prime place", "p-次数", "p-次數", "The degree of the corresponding completed field extension at the specified prime place.", "global field degree; polynomial degree; valuation order; exponent", "p-局部次数; p-度", "mixed/contested", "High: 次数 is Mandarin-dominant but competes with 度 and can collide with powers; the local formula supplies scope.", "Not generalized outside the local-degree passages."),
    t("segments A-C", "p-Index", "local Schur index of the completed algebra", "p-指标", "p-指標", "The index of the algebra after extension to the completion at the prime place $p$.", "array index; subgroup index; global algebra index; economic indicator", "p-指数; p-局部指标", "mixed/contested", "High: 指标 is used to distinguish Index from Exponent, but many Mandarin sources use 指数 for both or for Index; regional convention is untested.", "Kept distinct from the producer's 指数 for Exponent."),
    t("segments A-B", "auflösbarer Zerfällungskörper", "splitting field with solvable Galois group", "可解分裂域", "可解分裂域", "A splitting field whose relevant Galois group is solvable, enabling the chain of cyclic prime-degree extensions.", "a field in which equations are computationally solvable; a resolved physical region; algebraic closure", "可解群分裂域; 可解劈裂域", "modern Sino-xenic coinage/calque", "Medium: 可解 is standard Mainland group-theory language but the implicit Galois-group subject can be obscured; regional terminology is untested.", "The following field chain supplies the group-theoretic sense."),
    t("segment A reduction 2", "Sylowkörper", "fixed field of a Sylow subgroup", "Sylow 域", "Sylow 域", "The invariant field of a Sylow subgroup of the Galois group, relative to the chosen prime $p$.", "a field named after an unrelated construction; a Sylow subgroup itself; a finite field", "西罗域; Sylow 不变域", "global modern loan", "High: Sylow 域 is a producer compression and may be opaque; explicit 不变域 is a held alternative and regional naming is untested.", "The parenthetical definition is retained."),
    t("segment A reduction 3", "Faktorensystem", "factor set in the cyclic/crossed-product algebra construction", "因子系", "因子系", "The multiplication factor system used to present the associated crossed product or cyclic algebra.", "a generic system of factors; numerical factorization; quotient system without cocycle structure", "因子系统; 乘法因子集; 2-余循环", "modern Sino-xenic coinage/calque", "High: 因子系 is historically compact and Mainland-oriented; modern or regional shelves may prefer a longer or cohomological term.", "Historical register retained without modernization."),
    t("segment B norm argument", "Hassescher Normensatz", "Hasse norm theorem", "Hasse 范数定理", "Hasse 範數定理", "The local-global norm theorem invoked for cyclic extensions, including the prime-degree Hilbert-Furtwängler case.", "a vector-norm theorem; Hasse's unrelated local theorem; a normalization statement", "哈塞范数定理; Hasse 诺姆定理", "global modern loan", "Medium: retaining Hasse in Latin script avoids transliteration variation; 范数 is Mainland-dominant and regional naming is untested.", "Distinguished from the norm-residue symbol."),
    t("segments B-C", "Normenrestsymbol", "norm-residue symbol controlling local splitting", "范数剩余符号", "範數剩餘符號", "The local norm-residue symbol whose order gives the local index and which satisfies the product theorem.", "a remainder after numerical division; a generic norm sign; a residue-class norm without the local symbol", "范数留数符号; 诺姆剩余符号", "modern Sino-xenic coinage/calque", "High: 剩余/留数 traditions differ and the long compound is Mainland-oriented; regional evidence is absent.", "Formula notation is preserved beside the term."),
    t("segment A supplement; segment B theorem 1", "Exponent", "Brauer-group exponent of an algebra class", "指数", "指數", "The order/exponent of the algebra's Brauer class, asserted equal to the algebra index over a number field.", "a power in elementary algebra; an exponential function; a book superscript; the local algebra index", "周期; 类指数", "mixed/contested", "High: 指数 also translates mathematical exponent and is easily confused with Index; the target deliberately pairs 指数 with 指标.", "Checker must preserve the Exponent/Index distinction."),
    t("segments A-C", "Index", "degree of the associated division algebra / Schur index", "指标", "指標", "The algebra index, globally or after local completion, paired with Exponent in theorem 1.", "an economic indicator; subgroup index; an array position; Brauer-class exponent", "指数; Schur 指数", "mixed/contested", "High: 指标 is chosen to avoid collision with Exponent=指数, but differs from common Chinese algebra usage where Index may also be 指数.", "Deliberate producer disambiguation; independent review required."),
    t("segment B theorem 2 and segment C", "Grundideal", "Hasse's base/fundamental ideal of a division algebra", "基本理想", "基本理想", "The ideal defined via the reduced norm of the reduced different, with explicit warning against Dedekind's other use.", "an arbitrary basic ideal; the unit ideal; Dedekind's Grundideal for different/discriminant; a foundational principle", "基理想; 基础理想; 基准理想", "mixed/contested", "High: 基本理想 is literal and Mandarin-oriented while the source itself warns of terminological collision; regional evidence is absent.", "The warning footnote is preserved for checker review."),
    t("segment B theorem 2 footnote", "(reduzierte) Differente", "reduced different of a noncommutative order/algebra", "（约化）不同", "（約化）不同", "The reduced noncommutative analogue of the different used to define the fundamental ideal.", "ordinary difference; a derivative; the unreduced commutative different without qualification", "（约化）不同理想; （约化）差异理想", "mixed/contested", "High: 不同 is a specialized Mainland algebraic-number-theory term that is opaque in ordinary Chinese and regionally untested.", "Qualifying 约化 is retained."),
    t("segments A-C", "Primstelle", "finite or infinite place of a number field", "素位", "素位", "A prime place, including finite primes and infinite places, at which the algebra is completed.", "a prime ideal only; a physical position; a decimal place; a rank", "素点; 素处; 赋值位", "modern Sino-xenic coinage/calque", "High: 素位 is concise Mainland terminology but may be confused with prime ideals; finite/infinite distinctions require context and regional usage is untested.", "Kept distinct from 素因子/素理想."),
    t("segment B theorem 3 proof", "unverzweigter Körper", "unramified extension field of a local field", "未分歧域", "未分歧域", "The unique unramified extension of the local field of the stated degree.", "a topologically unbranched region; a field with no global ramification anywhere; a separable field generally", "非分歧域; 不分歧扩张", "modern Sino-xenic coinage/calque", "Medium: 未分歧 follows Mainland number-theory usage; 非分歧 is a live alternative and regional preference is untested.", "Target also says 未分歧扩张 in the argument."),
    t("segment B theorem 3 proof", "Kompositum", "compositum of two local fields", "复合域", "複合域", "The smallest field containing both $K_{P_i}$ and $W_p$ in a common overfield.", "a composite number field in the sense of nonprime degree; a function composition; a direct product", "合成域; 合域", "modern Sino-xenic coinage/calque", "Medium: 复合域 is Mainland-dominant but regional and older terminology are untested.", "Used only for the displayed local-field compositum."),
    t("segments B-C", "Verzweigungsordnung", "ramification index/order at a prime", "分歧指数", "分歧指數", "The ramification index $e_{P_i}$ in the prime decomposition and local-degree formula.", "order of a branch in graph theory; valuation order of an element; the exponent of an algebra class", "分歧阶; 分歧次数", "mixed/contested", "High: the assembled target uses 分歧指数 in theorem 3 and later 分歧阶 in theorem 6; this unadjudicated producer variation is left explicit for independent checking.", "No silent harmonization was performed."),
    t("segment C Brauer-group paragraph", "Brauersche Gruppe", "Brauer group of similarity classes of algebras", "R. Brauer 的群", "R. Brauer 的群", "The group of similarity classes of algebras over the base field, with a subgroup determined by the splitting field $K$.", "the group of people belonging to Brauer; a Galois group; one algebra rather than its class", "Brauer 群; 布劳尔群", "global modern loan", "High: the producer retains the source's personal-name possessive instead of modern Brauer 群; terminology and regional name convention are untested.", "The parenthetical class definition remains in the text."),
    t("segment C theorem 4", "Zerlegungssatz", "decomposition theorem relating residue degree to local algebra exponents", "分解定理", "分解定理", "The theorem identifying the residue degree of prime factors in $K$ with the least exponent splitting all corresponding local algebras.", "primary decomposition; decomposition of representations; a generic factorization theorem", "分裂定理; 素分解定理", "modern Sino-xenic coinage/calque", "High: 分解定理 has many Mandarin mathematical attractors; the theorem's explicit statement fixes the local class-field sense.", "Bound to theorem 4 only."),
    t("segment C theorem 5", "Eindeutigkeits- und Anordnungssatz", "uniqueness-and-order theorem for field/group inclusion correspondence", "唯一性与序定理", "唯一性與序定理", "The theorem asserting $K\\leqq K'$ iff the associated algebra subgroups satisfy the same inclusion.", "an ordering algorithm; uniqueness of factorization; total-order theorem", "唯一性和包含关系定理; 唯一与次序定理", "modern Sino-xenic coinage/calque", "Medium: 序 is compact Mainland prose and may understate inclusion-order content; regional wording is untested.", "The displayed inclusions supply the precise sense."),
    t("segment C theorem 6", "Kreiskörper", "cyclotomic field generated by roots of unity", "圆分域", "圓分域", "A cyclotomic field in which the absolutely irreducible representations can be realized.", "a circular geometric region; an arbitrary cyclic field; a quotient field", "分圆域; 圆分体; cyclotomic 域", "mixed/contested", "High: the target uses 圆分域 while earlier Chinese shelves may use 分圆域; Traditional regional convention is unresearched.", "The $n^h$-th roots-of-unity description fixes the concept."),
    t("segment C theorem 6 proof", "halbeinfache Algebra", "semisimple group algebra", "半单代数", "半單代數", "The rational group algebra decomposed into simple components carrying the absolutely irreducible representations.", "an algebra that is merely not fully simple; a half-sized algebra; a simple algebra", "半单环; 完全可约代数", "modern Sino-xenic coinage/calque", "Medium: 半单代数 follows Mainland usage but its relationship to historical completely reducible language and regional terminology is untested.", "Used for the rational group ring in the final proof."),
]


TERM_FIELDS = ["decision_id","source_locator","exact_german_phrase","concept_scope","zh_hans_cn_choice","sense_window","excluded_senses","alternatives_considered","lexical_attractor_basin","mandarin_simplified_dominance_risk_debt","evidence_class","controlled_hant_form","controlled_hant_status","independent_check_status","producer_note"]
ADV_FIELDS = ["adverse_id","term_decision_id","source_locator","exact_german_phrase","zh_hans_cn_producer_choice","trap_or_adverse_reading","contextual_reason_for_exclusion","alternative_held_for_independent_review","lexical_attractor_basin","mandarin_simplified_dominance_risk_debt","evidence_class","controlled_hant_status","review_state"]
CROSS_FIELDS = ["crosswalk_id","term_decision_id","source_locator","exact_german_phrase","zh_hans_cn_producer_form","zh_hant_controlled_form","zh_hant_status","ja_form","ko_form","ja_ko_evidence_status","sense_window","excluded_senses","lexical_attractor_basin","mandarin_simplified_dominance_risk_debt","evidence_class","independent_check_status"]


def write_csv(path: Path, fields: list[str], rows: list[dict[str, str]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields, quoting=csv.QUOTE_ALL, lineterminator="\n")
        w.writeheader(); w.writerows(rows)


term_rows, adv_rows, cross_rows, nodes, edges = [], [], [], [], []
for i, x in enumerate(TERMS, 1):
    n = f"{i:03d}"; decision = f"P38-ZH-T{n}"
    term_rows.append({"decision_id":decision,"source_locator":x["locator"],"exact_german_phrase":x["german"],"concept_scope":x["scope"],"zh_hans_cn_choice":x["hans"],"sense_window":x["window"],"excluded_senses":x["excluded"],"alternatives_considered":x["alternatives"],"lexical_attractor_basin":x["basin"],"mandarin_simplified_dominance_risk_debt":x["debt"],"evidence_class":EVIDENCE_CLASS,"controlled_hant_form":x["hant"],"controlled_hant_status":HANT_STATUS,"independent_check_status":REVIEW,"producer_note":x["note"]})
    adv_rows.append({"adverse_id":f"P38-ZH-A{n}","term_decision_id":decision,"source_locator":x["locator"],"exact_german_phrase":x["german"],"zh_hans_cn_producer_choice":x["hans"],"trap_or_adverse_reading":x["excluded"],"contextual_reason_for_exclusion":x["window"],"alternative_held_for_independent_review":x["alternatives"],"lexical_attractor_basin":x["basin"],"mandarin_simplified_dominance_risk_debt":x["debt"],"evidence_class":EVIDENCE_CLASS,"controlled_hant_status":HANT_STATUS,"review_state":REVIEW})
    cross_rows.append({"crosswalk_id":f"P38-ZH-X{n}","term_decision_id":decision,"source_locator":x["locator"],"exact_german_phrase":x["german"],"zh_hans_cn_producer_form":x["hans"],"zh_hant_controlled_form":x["hant"],"zh_hant_status":HANT_STATUS,"ja_form":"","ko_form":"","ja_ko_evidence_status":"JA and KO not consulted and not authorized as Chinese evidence","sense_window":x["window"],"excluded_senses":x["excluded"],"lexical_attractor_basin":x["basin"],"mandarin_simplified_dominance_risk_debt":x["debt"],"evidence_class":EVIDENCE_CLASS,"independent_check_status":REVIEW})
    loc=f"P38-LOC-{n}"; con=f"P38-CON-{n}"; hans=f"P38-HANS-{n}"; hant=f"P38-HANT-{n}"; choice=f"P38-CHOICE-{n}"
    nodes += [{"id":loc,"type":"source_locus","locator":x["locator"],"exact_german_phrase":x["german"]},{"id":con,"type":"concept","scope":x["scope"],"sense_window":x["window"],"excluded_senses":x["excluded"]},{"id":hans,"type":"form","language_scope":"zh-Hans-CN producer","form":x["hans"]},{"id":hant,"type":"form","language_scope":"zh-Hant-controlled nonregional producer record","form":x["hant"],"status":HANT_STATUS},{"id":choice,"type":"producer_choice","decision_id":decision,"dominance_risk_debt":x["debt"],"evidence_class":EVIDENCE_CLASS,"review_state":REVIEW}]
    edges += [{"id":f"P38-E{n}-1","type":"occurs_at","from":con,"to":loc},{"id":f"P38-E{n}-2","type":"decides_for","from":choice,"to":con},{"id":f"P38-E{n}-3","type":"selects_hans_form","from":choice,"to":hans},{"id":f"P38-E{n}-4","type":"records_controlled_hant_form","from":choice,"to":hant},{"id":f"P38-E{n}-5","type":"controlled_form_of","from":hant,"to":hans}]

write_csv(OUT/"TERMINOLOGY_LEDGER.csv", TERM_FIELDS, term_rows)
write_csv(OUT/"ADVERSE_EVIDENCE_LEDGER.csv", ADV_FIELDS, adv_rows)
write_csv(OUT/"CJKV_CROSSWALK.csv", CROSS_FIELDS, cross_rows)

graph = {
  "graph_id":"NOE-P38-ZH-PRODUCER-CONCEPT-GRAPH-001",
  "work_unit":"Noether Paper 38 Chinese producer translation",
  "graph_status":{"purpose":"producer-side translation-decision evidence only","decision_count":len(TERMS),"independent_check":"absent","external_native_source_research":"not performed","japanese_or_korean_evidence":"not consulted or used","scan_inspection":"not performed","source_branch_comparison":"not performed; known apparatus history not adjudicated","compilation_or_rendering":"mechanical XeLaTeX completed; rendered pages not inspected","controlled_hant_scope":HANT_STATUS,"translation_validation_or_readiness_claim":"none"},
  "provenance":{"german_snapshot":{"path":"source/Noether_Paper38_German_current_exact_CRLF.tex","sha256":SOURCE_SHA,"use":"translation source wording and locator only; no source/apparatus check"},"inherited_hans_witness":{"path":"witness/Noether_Paper38_SimplifiedChinese_inherited_exact_CRLF.tex","sha256":WITNESS_SHA,"use":"drafting witness only; not authority"},"hans_target":{"path":"zh-Hans-CN/Noether_Paper38_Chinese_CurrentAuthority_zh-Hans-CN_v001.tex","sha256":HANS_SHA,"use":"producer choice record; independent check absent"},"controlled_hant_target":{"path":"zh-Hant-controlled/Noether_Paper38_Chinese_CurrentAuthority_zh-Hant-controlled_v001.tex","sha256":HANT_SHA,"use":HANT_STATUS},"evidence_class":EVIDENCE_CLASS},
  "node_type_definitions":{"source_locus":"Locator and phrase in the supplied German fragments; not a source-validation assertion.","concept":"Producer's bounded sense window and excluded lexical attractors.","form":"Proposed Chinese form with explicit Hans or nonregional controlled-Hant scope.","producer_choice":"Editorial selection with qualitative Mandarin-Simplified dominance debt and open review state; lexical-attractor basin is recorded only in the CSV ledgers."},
  "edge_type_definitions":{"occurs_at":"Concept to supplied-source locator.","decides_for":"Producer choice to concept.","selects_hans_form":"Producer choice to Hans form.","records_controlled_hant_form":"Producer choice to nonregional controlled-Hant form.","controlled_form_of":"Controlled-Hant script form to Hans lexical base without Taiwan/Hong Kong/Macao equivalence claim."},
  "nodes":nodes,"edges":edges,
}
(OUT/"CONCEPT_EVIDENCE_GRAPH.json").write_text(json.dumps(graph,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")


def sha(p: Path) -> str: return hashlib.sha256(p.read_bytes()).hexdigest().upper()
print(json.dumps({"term_rows":len(term_rows),"adverse_rows":len(adv_rows),"crosswalk_rows":len(cross_rows),"graph_nodes":len(nodes),"graph_edges":len(edges),"hashes":{p.name:sha(p) for p in sorted(OUT.iterdir()) if p.is_file()},"claim_limit":"Producer decision recording only; no independent checking or readiness claim."},ensure_ascii=False,indent=2))
