#!/usr/bin/env python3
"""Build the SGA6 idx354-361 targeted-crop backfill release.

This release closes a narrow gap in the first crop snapshot. It publishes the
tight symbol/formula crops that were actually generated and read during the
July 10 source repair, but it keeps both generations of full-width page bands
as hash-only rights-blocked metadata.
"""

from __future__ import annotations

import argparse
import ast
import csv
import hashlib
import importlib.util
import json
import re
import sys
import zipfile
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import fitz
from PIL import Image, ImageChops, ImageEnhance, ImageOps


PACKAGE_TAG = "idx354_361"
DATE_TAG = "20260724"
TARGET_ZIP = (
    "10t_SGA6_SourceAudit_Targeted_HighDetail_Crops_Backfill_"
    f"{PACKAGE_TAG}_{DATE_TAG}.zip"
)
METADATA_ZIP = (
    "10u_SGA6_SourceAudit_Crop_Provenance_RightsBlocked_Metadata_Backfill_"
    f"{PACKAGE_TAG}_{DATE_TAG}.zip"
)
README_NAME = (
    f"SGA6_Targeted_HighDetail_Crops_Backfill_{PACKAGE_TAG}_README_{DATE_TAG}.md"
)
PARENT_NAME = (
    f"SGA6_Targeted_HighDetail_Crops_Backfill_{PACKAGE_TAG}_"
    f"PARENT_SOURCE_{DATE_TAG}.json"
)
TARGET_MANIFEST_NAME = (
    f"SGA6_Targeted_HighDetail_Crops_Backfill_{PACKAGE_TAG}_"
    f"Manifest_{DATE_TAG}.csv"
)
BLOCKED_MANIFEST_NAME = (
    f"SGA6_PageBands_{PACKAGE_TAG}_RightsBlocked_Manifest_{DATE_TAG}.csv"
)
AUDIT_CONTEXT_NAME = (
    f"SGA6_Targeted_HighDetail_Crops_Backfill_{PACKAGE_TAG}_"
    f"Audit_Context_{DATE_TAG}.csv"
)
VALIDATION_NAME = (
    f"SGA6_Targeted_HighDetail_Crops_Backfill_{PACKAGE_TAG}_"
    f"VALIDATION_{DATE_TAG}.json"
)
UPLOAD_MANIFEST_NAME = (
    f"SGA6_Targeted_HighDetail_Crops_Backfill_{PACKAGE_TAG}_"
    f"ZENODO_UPLOAD_MANIFEST_{DATE_TAG}.csv"
)
SHA_NAME = (
    f"SGA6_Targeted_HighDetail_Crops_Backfill_{PACKAGE_TAG}_"
    f"SHA256SUMS_{DATE_TAG}.txt"
)

PARENT_SHA256 = "73FBBAD41340C12ECCDCFCF6C3A1656953FE3D712AA8E391678458CCD17B4BAA"
PGCROP_SHA256 = "553A9DEADEBA92AB2FE2E28C56BE76C9373B21F5F8887C3865FD0E03B058271C"
START_INDEX = 354
END_INDEX = 361
PRINTED_OFFSET = 13
HISTORICAL_RENDER_DPI = 500
HISTORICAL_BAND_COUNT = 5

PRIVATE_MARKERS = (
    "c:\\users\\",
    "floris",
    "chatnotes",
    "claude",
    "codex",
    "thread_id",
    "source_thread_id",
    "@gmail.",
    "@outlook.",
)
FORMULA_PREFIXES = ("=", "+", "-", "@")

EXPECTED_TARGETS = {
    "c354_552.png",
    "c356_561tag.png",
    "c356_binom.png",
    "c356_gk.png",
    "c357_grp2.png",
    "c358_612.png",
    "c358_612b.png",
    "c358_disp1.png",
    "c358_disp2.png",
    "c358_fonct.png",
    "c358_obc.png",
    "c358_obc2.png",
    "c359_disp1.png",
    "c359_disp2.png",
    "c359_disp2b.png",
    "c359_gp_top.png",
    "c359_surcg.png",
    "c359_surcg2.png",
    "c360_621.png",
    "c360_621end.png",
    "c360_obcg.png",
    "c361_adots.png",
    "c361_chXa.png",
    "c361_etadot.png",
    "c361_tensor.png",
}

# Five crops were generated by inline Python commands. The command text stays
# private; its exact UTF-8 SHA-256, transcript line, timestamp, and crop
# parameters are durable public provenance.
INLINE_SPECS: dict[str, dict[str, object]] = {
    "c358_obc2.png": {
        "source_band": "p358_b3.png",
        "bbox": [640, 400, 1050, 620],
        "scale": 7,
        "command_sha256": (
            "F240F63772BC1495679AD5A91E73FBB36726F7D8934FE95B172455E5F1A65469"
        ),
        "command_bytes": 496,
        "transcript_line": 103271,
        "timestamp": "2026-07-10T19:14:48.571Z",
    },
    "c358_612b.png": {
        "source_band": "p358_b4.png",
        "bbox": [1050, 250, 2050, 470],
        "scale": 5,
        "command_sha256": (
            "4A13C9DFC5C9144E8BED3CF3DCC3A22ED622D1DB74D80506BB86FCAB0338A96D"
        ),
        "command_bytes": 497,
        "transcript_line": 103289,
        "timestamp": "2026-07-10T19:15:17.142Z",
    },
    "c359_surcg2.png": {
        "source_band": "p359_b2.png",
        "bbox": [1300, 600, 2200, 760],
        "scale": 5,
        "command_sha256": (
            "0C069C7C602F86B3B6A4E061129E42F83E69EAB4A49C7C04D791AABB5EA77CF5"
        ),
        "command_bytes": 796,
        "transcript_line": 103438,
        "timestamp": "2026-07-10T19:27:23.814Z",
    },
    "c359_disp2b.png": {
        "source_band": "p359_b2.png",
        "bbox": [700, 760, 2100, 960],
        "scale": 5,
        "command_sha256": (
            "0C069C7C602F86B3B6A4E061129E42F83E69EAB4A49C7C04D791AABB5EA77CF5"
        ),
        "command_bytes": 796,
        "transcript_line": 103438,
        "timestamp": "2026-07-10T19:27:23.814Z",
    },
    "c360_621end.png": {
        "source_band": "p360_b2.png",
        "bbox": [1700, 250, 2250, 400],
        "scale": 6,
        "command_sha256": (
            "A9871B7E3AE6D5ECB65D6CC2EB778BD9D4F575BF5CDC6B0589663B0309A8596E"
        ),
        "command_bytes": 488,
        "transcript_line": 103576,
        "timestamp": "2026-07-10T19:39:56.154Z",
    },
}

COLD_BBOXES = {
    "top": (0.03, 0.015, 0.98, 0.10),
    "a": (0.03, 0.03, 0.98, 0.29),
    "b": (0.03, 0.27, 0.98, 0.53),
    "c": (0.03, 0.51, 0.98, 0.77),
    "d": (0.03, 0.75, 0.98, 0.99),
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--scratch-dir", type=Path, required=True)
    parser.add_argument("--script-dir", type=Path, required=True)
    parser.add_argument("--parent-pdf", type=Path, required=True)
    parser.add_argument("--cert-log", type=Path, required=True)
    parser.add_argument(
        "--prior-package-dir",
        type=Path,
        required=True,
        action="append",
    )
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--zip-dir", type=Path, required=True)
    return parser.parse_args()


def load_base_module() -> Any:
    base_path = (
        Path(__file__).resolve().parent.parent
        / "sga6-high-detail-source-audit-crops-coldreverify-idx349-353-20260724"
        / "build_release.py"
    )
    spec = importlib.util.spec_from_file_location("sga6_crop_base", base_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load shared crop helpers: {base_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


BASE = load_base_module()


def sha256(path: Path) -> str:
    return str(BASE.sha256(path))


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest().upper()


def utc_mtime(path: Path) -> str:
    return datetime.fromtimestamp(
        path.stat().st_mtime, timezone.utc
    ).isoformat()


def write_text(path: Path, text: str) -> None:
    path.write_bytes(text.encode("utf-8"))


def write_csv(
    path: Path,
    rows: list[dict[str, object]],
    fields: list[str],
) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle, fieldnames=fields, lineterminator="\n"
        )
        writer.writeheader()
        writer.writerows(rows)


def png_metadata(path: Path) -> dict[str, object]:
    Image.MAX_IMAGE_PIXELS = None
    with Image.open(path) as image:
        image.verify()
    with Image.open(path) as image:
        dpi = image.info.get("dpi")
        return {
            "width_px": image.width,
            "height_px": image.height,
            "color_mode": image.mode,
            "embedded_dpi_x": round(float(dpi[0]), 4) if dpi else "",
            "embedded_dpi_y": round(float(dpi[1]), 4) if dpi else "",
            "metadata_text": json.dumps(
                {str(k): str(v) for k, v in image.info.items()},
                sort_keys=True,
                ensure_ascii=True,
            ),
        }


def privacy_hits(values: list[str]) -> list[str]:
    joined = "\n".join(values).lower()
    return sorted(marker for marker in PRIVATE_MARKERS if marker in joined)


def literal(node: ast.AST) -> object | None:
    try:
        return ast.literal_eval(node)
    except (ValueError, TypeError):
        return None


def parse_script_target_specs(script_dir: Path) -> dict[str, dict[str, object]]:
    specs: dict[str, dict[str, object]] = {}
    output_re = re.compile(
        r"^c(?:354|355|356|357|358|359|360|361)_.*\.png$",
        re.IGNORECASE,
    )
    for script in script_dir.glob("*.py"):
        text = script.read_text(encoding="utf-8-sig", errors="replace")
        try:
            tree = ast.parse(text)
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if (
                not isinstance(node, ast.Call)
                or not isinstance(node.func, ast.Name)
                or node.func.id != "crop"
                or len(node.args) < 6
            ):
                continue
            values = [literal(arg) for arg in node.args]
            if any(value is None for value in values[:6]):
                continue
            output = str(values[5])
            if not output_re.fullmatch(output):
                continue
            scale = int(values[6]) if len(values) >= 7 else 5
            if output in specs:
                raise ValueError(f"duplicate script target specification: {output}")
            specs[output] = {
                "source_band": str(values[0]),
                "bbox": [int(value) for value in values[1:5]],
                "scale": scale,
                "generator_kind": "saved_python_script",
                "generator_basename": script.name,
                "generator_sha256": sha256(script),
                "generator_bytes": script.stat().st_size,
                "generator_modified_utc": utc_mtime(script),
                "generator_line": node.lineno,
            }
    return specs


def clamp_bbox(
    bbox: list[int],
    width: int,
    height: int,
) -> tuple[int, int, int, int]:
    x0, y0, x1, y1 = bbox
    return (
        max(0, min(x0, width)),
        max(0, min(y0, height)),
        max(0, min(x1, width)),
        max(0, min(y1, height)),
    )


def band_bounds(full_height: int, band_number: int) -> tuple[int, int]:
    overlap = int(full_height / HISTORICAL_BAND_COUNT * 0.10)
    start = max(
        0,
        int(full_height * (band_number - 1) / HISTORICAL_BAND_COUNT)
        - overlap,
    )
    end = min(
        full_height,
        int(full_height * band_number / HISTORICAL_BAND_COUNT) + overlap,
    )
    return start, end


def render_historical_page(page: fitz.Page) -> Image.Image:
    pixmap = page.get_pixmap(
        matrix=fitz.Matrix(
            HISTORICAL_RENDER_DPI / 72.0,
            HISTORICAL_RENDER_DPI / 72.0,
        ),
        colorspace=fitz.csGRAY,
    )
    image = Image.frombytes(
        "L",
        [pixmap.width, pixmap.height],
        pixmap.samples,
    )
    image = ImageOps.autocontrast(image, cutoff=1)
    image = ImageEnhance.Contrast(image).enhance(2.0)
    image = ImageEnhance.Sharpness(image).enhance(1.7)
    return image


def image_pixels_equal(left: Image.Image, right: Image.Image) -> bool:
    if left.mode != right.mode or left.size != right.size:
        return False
    return ImageChops.difference(left, right).getbbox() is None


def audit_rows_for_indices(
    cert_bytes: bytes,
) -> tuple[
    list[dict[str, object]],
    dict[int, dict[str, object]],
    dict[int, dict[str, object]],
]:
    all_rows, _latest = BASE.parse_audit_context(cert_bytes)
    selected: list[dict[str, object]] = []
    original: dict[int, dict[str, object]] = {}
    cold: dict[int, dict[str, object]] = {}
    for index in range(START_INDEX, END_INDEX + 1):
        rows = [
            row
            for row in all_rows
            if int(row["parent_pdf_index_0based"]) == index
        ]
        original_rows = [
            row
            for row in rows
            if "2026-07-10" in str(row["audit_heading"])
        ]
        cold_rows = [
            row
            for row in rows
            if "2026-07-24" in str(row["audit_heading"])
            and "COLD RE-VERIFY" in str(row["audit_heading"])
        ]
        if original_rows:
            original[index] = max(
                original_rows,
                key=lambda row: int(row["audit_entry_number"]),
            )
            selected.append(original[index])
        if cold_rows:
            cold[index] = max(
                cold_rows,
                key=lambda row: int(row["audit_entry_number"]),
            )
            selected.append(cold[index])
    selected.sort(
        key=lambda row: (
            int(row["parent_pdf_index_0based"]),
            int(row["audit_entry_number"]),
        )
    )
    return selected, original, cold


def prior_target_hashes(prior_dirs: list[Path]) -> set[str]:
    digests: set[str] = set()
    for prior_dir in prior_dirs:
        for path in prior_dir.glob("*Targeted*Manifest*.csv"):
            with path.open("r", encoding="utf-8-sig", newline="") as handle:
                for row in csv.DictReader(handle):
                    digest = row.get("sha256", "").upper()
                    if digest:
                        digests.add(digest)
    return digests


def zip_payload(
    path: Path,
    image_rows: list[dict[str, object]],
    scratch_dir: Path,
    metadata_paths: list[Path],
) -> dict[str, object]:
    expected: dict[str, tuple[int, str]] = {}
    path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(
        path,
        "w",
        compression=zipfile.ZIP_DEFLATED,
        compresslevel=6,
        allowZip64=True,
    ) as archive:
        for row in image_rows:
            source = scratch_dir / str(row["source_basename"])
            member = str(row["archive_path"])
            archive.write(source, member)
            expected[member] = (int(row["bytes"]), str(row["sha256"]))
        for source in metadata_paths:
            member = f"metadata/{source.name}"
            archive.write(source, member)
            expected[member] = (source.stat().st_size, sha256(source))
    errors: list[str] = []
    members: list[dict[str, object]] = []
    with zipfile.ZipFile(path) as archive:
        bad = archive.testzip()
        if bad:
            errors.append(f"CRC failure: {bad}")
        names = [info.filename for info in archive.infolist()]
        if len(names) != len(set(names)):
            errors.append("duplicate ZIP member")
        if set(names) != set(expected):
            errors.append(
                f"ZIP exact-set mismatch: missing={sorted(set(expected)-set(names))}; "
                f"extra={sorted(set(names)-set(expected))}"
            )
        for info in archive.infolist():
            if info.filename.startswith("/") or ".." in Path(info.filename).parts:
                errors.append(f"unsafe ZIP member: {info.filename}")
            data = archive.read(info.filename)
            identity = (len(data), sha256_bytes(data))
            if info.filename in expected and identity != expected[info.filename]:
                errors.append(f"ZIP member identity mismatch: {info.filename}")
            members.append(
                {
                    "path": info.filename,
                    "bytes": identity[0],
                    "sha256": identity[1],
                }
            )
    return {
        "filename": path.name,
        "bytes": path.stat().st_size,
        "sha256": sha256(path),
        "members": len(members),
        "image_members": len(image_rows),
        "uncompressed_bytes": sum(int(row["bytes"]) for row in members),
        "errors": errors,
    }


def formula_triggers(path: Path) -> list[str]:
    triggers: list[str] = []
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        for row_number, row in enumerate(reader, start=2):
            for field, value in row.items():
                if value and value.startswith(FORMULA_PREFIXES):
                    triggers.append(f"{row_number}:{field}:{value[:32]}")
    return triggers


def main() -> int:
    args = parse_args()
    scratch_dir = args.scratch_dir.resolve()
    script_dir = args.script_dir.resolve()
    parent_pdf = args.parent_pdf.resolve()
    cert_log = args.cert_log.resolve()
    prior_package_dirs = [path.resolve() for path in args.prior_package_dir]
    output_dir = args.output_dir.resolve()
    zip_dir = args.zip_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    zip_dir.mkdir(parents=True, exist_ok=True)

    errors: list[str] = []
    if sha256(parent_pdf) != PARENT_SHA256:
        errors.append("parent PDF identity mismatch")
    pgcrop_path = script_dir / "pgcrop.py"
    if not pgcrop_path.is_file() or sha256(pgcrop_path) != PGCROP_SHA256:
        errors.append("historical page-band generator identity mismatch")

    cert_bytes = cert_log.read_bytes()
    cert_sha = sha256_bytes(cert_bytes)
    audit_rows, original_audit, cold_audit = audit_rows_for_indices(cert_bytes)
    for index in range(START_INDEX, END_INDEX + 1):
        if index not in original_audit:
            errors.append(f"missing original audit context for idx{index}")
        if index not in cold_audit:
            errors.append(f"missing cold-reverify audit context for idx{index}")

    specs = parse_script_target_specs(script_dir)
    for name, inline in INLINE_SPECS.items():
        if name in specs:
            errors.append(f"inline target duplicates script target: {name}")
        specs[name] = {
            "source_band": inline["source_band"],
            "bbox": inline["bbox"],
            "scale": inline["scale"],
            "generator_kind": "inline_python_command",
            "generator_basename": (
                f"inline_generator_transcript_line_{inline['transcript_line']}.command"
            ),
            "generator_sha256": inline["command_sha256"],
            "generator_bytes": inline["command_bytes"],
            "generator_modified_utc": inline["timestamp"],
            "generator_line": inline["transcript_line"],
        }
    actual_targets = set(specs)
    if actual_targets != EXPECTED_TARGETS:
        errors.append(
            "target specification set mismatch: "
            f"missing={sorted(EXPECTED_TARGETS-actual_targets)}; "
            f"extra={sorted(actual_targets-EXPECTED_TARGETS)}"
        )

    initial_files: dict[str, tuple[int, int, str]] = {}
    all_source_names = set(EXPECTED_TARGETS)
    all_source_names.update(
        f"p{index}_b{band}.png"
        for index in range(START_INDEX, END_INDEX + 1)
        for band in range(1, HISTORICAL_BAND_COUNT + 1)
    )
    all_source_names.update(
        f"cve0p{index}_{tag}.png"
        for index in range(START_INDEX, END_INDEX + 1)
        for tag in COLD_BBOXES
    )
    for name in sorted(all_source_names):
        path = scratch_dir / name
        if not path.is_file():
            errors.append(f"missing source image: {name}")
            continue
        stat = path.stat()
        initial_files[name] = (stat.st_size, stat.st_mtime_ns, sha256(path))

    historical_band_meta: dict[str, dict[str, object]] = {}
    historical_replay_errors: list[str] = []
    parent_dimensions: dict[int, tuple[int, int]] = {}
    Image.MAX_IMAGE_PIXELS = None
    with fitz.open(parent_pdf) as document:
        if document.page_count != 720:
            errors.append(f"parent page count is {document.page_count}, expected 720")
        for index in range(START_INDEX, END_INDEX + 1):
            rendered = render_historical_page(document[index])
            parent_dimensions[index] = rendered.size
            for band_number in range(1, HISTORICAL_BAND_COUNT + 1):
                name = f"p{index}_b{band_number}.png"
                source_path = scratch_dir / name
                if not source_path.is_file():
                    continue
                y0, y1 = band_bounds(rendered.height, band_number)
                expected_band = rendered.crop((0, y0, rendered.width, y1))
                with Image.open(source_path) as actual_band:
                    actual = actual_band.convert("L")
                    if not image_pixels_equal(expected_band, actual):
                        historical_replay_errors.append(
                            f"parent-to-band pixel mismatch: {name}"
                        )
                meta = png_metadata(source_path)
                historical_band_meta[name] = {
                    **meta,
                    "parent_band_y0_px": y0,
                    "parent_band_y1_px": y1,
                    "parent_full_width_px": rendered.width,
                    "parent_full_height_px": rendered.height,
                }
    errors.extend(historical_replay_errors)

    target_rows: list[dict[str, object]] = []
    target_replay_errors: list[str] = []
    target_hashes_seen: set[str] = set()
    previous_hashes = prior_target_hashes(prior_package_dirs)
    for name in sorted(EXPECTED_TARGETS, key=str.lower):
        spec = specs.get(name)
        target_path = scratch_dir / name
        if spec is None or not target_path.is_file():
            continue
        source_band_name = str(spec["source_band"])
        band_path = scratch_dir / source_band_name
        match = re.fullmatch(r"p(\d+)_b([1-5])\.png", source_band_name)
        if not match or not band_path.is_file():
            errors.append(f"invalid or missing source band for {name}: {source_band_name}")
            continue
        index = int(match.group(1))
        band_number = int(match.group(2))
        band_meta = historical_band_meta[source_band_name]
        bbox = clamp_bbox(
            [int(value) for value in spec["bbox"]],  # type: ignore[index]
            int(band_meta["width_px"]),
            int(band_meta["height_px"]),
        )
        scale = int(spec["scale"])
        with Image.open(band_path) as source_band:
            replay = ImageOps.autocontrast(
                source_band.convert("L").crop(bbox)
            )
            replay = replay.resize(
                (replay.width * scale, replay.height * scale),
                Image.Resampling.LANCZOS,
            )
        with Image.open(target_path) as target:
            target_image = target.convert("L")
            if not image_pixels_equal(replay, target_image):
                target_replay_errors.append(
                    f"source-band-to-target pixel mismatch: {name}"
                )
        target_meta = png_metadata(target_path)
        target_digest = sha256(target_path)
        if target_digest in target_hashes_seen:
            errors.append(f"duplicate targeted image content: {name}")
        target_hashes_seen.add(target_digest)
        if target_digest in previous_hashes:
            errors.append(f"target already represented in prior snapshot: {name}")
        parent_width, parent_height = parent_dimensions[index]
        band_y0 = int(band_meta["parent_band_y0_px"])
        x0, y0, x1, y1 = bbox
        parent_bbox = (
            x0 / parent_width,
            (band_y0 + y0) / parent_height,
            x1 / parent_width,
            (band_y0 + y1) / parent_height,
        )
        target_rows.append(
            {
                "archive_path": f"images/targeted_backfill/{name}",
                "source_basename": name,
                "bytes": target_path.stat().st_size,
                "sha256": target_digest,
                "width_px": target_meta["width_px"],
                "height_px": target_meta["height_px"],
                "color_mode": target_meta["color_mode"],
                "embedded_dpi_x": target_meta["embedded_dpi_x"],
                "embedded_dpi_y": target_meta["embedded_dpi_y"],
                "modified_utc": utc_mtime(target_path),
                "category": "targeted_symbol_formula_crop_backfill",
                "public_disposition": (
                    "public_targeted_source_audit_evidence_no_license_grant"
                ),
                "parent_pdf_index_0based": index,
                "parent_pdf_page_1based": index + 1,
                "printed_page": index - PRINTED_OFFSET,
                "linked_tex_object": "sga6_fr_workpass.tex",
                "original_audit_entry": original_audit[index][
                    "audit_entry_number"
                ],
                "cold_reverify_audit_entry": cold_audit[index][
                    "audit_entry_number"
                ],
                "source_band_basename": source_band_name,
                "source_band_bytes": band_path.stat().st_size,
                "source_band_sha256": sha256(band_path),
                "source_band_width_px": band_meta["width_px"],
                "source_band_height_px": band_meta["height_px"],
                "source_band_public_disposition": "rights_blocked_not_public",
                "source_band_generator_basename": "pgcrop.py",
                "source_band_generator_sha256": PGCROP_SHA256,
                "source_band_render_dpi": HISTORICAL_RENDER_DPI,
                "source_band_number_of_five": band_number,
                "target_generator_kind": spec["generator_kind"],
                "target_generator_basename": spec["generator_basename"],
                "target_generator_sha256": spec["generator_sha256"],
                "target_generator_bytes": spec["generator_bytes"],
                "target_generator_modified_utc": spec[
                    "generator_modified_utc"
                ],
                "target_generator_line_or_transcript_line": spec[
                    "generator_line"
                ],
                "bbox_in_source_band_px": ",".join(str(value) for value in bbox),
                "bbox_coordinate_system": "fraction_of_parent_page",
                "bbox_x0": f"{parent_bbox[0]:.9f}",
                "bbox_y0": f"{parent_bbox[1]:.9f}",
                "bbox_x1": f"{parent_bbox[2]:.9f}",
                "bbox_y1": f"{parent_bbox[3]:.9f}",
                "target_upsample_factor": scale,
                "processing_profile": (
                    "parent_500dpi_grayscale_autocontrast_contrast2.0_"
                    "sharpness1.7;target_autocontrast_lanczos_upsample"
                ),
                "provenance_status": (
                    "pixel_exact_parent_to_band_and_band_to_target_replay"
                ),
                "qa_disposition": (
                    "read_in_source_repair_and_cold_reverified_"
                    "not_translation_certification"
                ),
                "parent_scan_sha256": PARENT_SHA256,
            }
        )
    errors.extend(target_replay_errors)
    if len(target_rows) != 25:
        errors.append(f"target row count is {len(target_rows)}, expected 25")

    blocked_rows: list[dict[str, object]] = []
    for index in range(START_INDEX, END_INDEX + 1):
        for band_number in range(1, HISTORICAL_BAND_COUNT + 1):
            name = f"p{index}_b{band_number}.png"
            path = scratch_dir / name
            if not path.is_file():
                continue
            meta = historical_band_meta[name]
            full_width, full_height = parent_dimensions[index]
            y0 = int(meta["parent_band_y0_px"])
            y1 = int(meta["parent_band_y1_px"])
            blocked_rows.append(
                {
                    "source_phase": "2026-07-10_source_repair",
                    "source_basename": name,
                    "bytes": path.stat().st_size,
                    "sha256": sha256(path),
                    "width_px": meta["width_px"],
                    "height_px": meta["height_px"],
                    "color_mode": meta["color_mode"],
                    "embedded_dpi_x": meta["embedded_dpi_x"],
                    "embedded_dpi_y": meta["embedded_dpi_y"],
                    "modified_utc": utc_mtime(path),
                    "category": "routine_page_band_derivative",
                    "public_disposition": "rights_blocked_not_public",
                    "parent_pdf_index_0based": index,
                    "parent_pdf_page_1based": index + 1,
                    "printed_page": index - PRINTED_OFFSET,
                    "linked_tex_object": "sga6_fr_workpass.tex",
                    "original_audit_entry": original_audit[index][
                        "audit_entry_number"
                    ],
                    "cold_reverify_audit_entry": cold_audit[index][
                        "audit_entry_number"
                    ],
                    "generator_basename": "pgcrop.py",
                    "generator_sha256": PGCROP_SHA256,
                    "generator_modified_utc": (
                        "verified_unchanged_from_2026-07-03_transcript_write"
                    ),
                    "bbox_coordinate_system": "fraction_of_parent_page",
                    "bbox_x0": "0.0",
                    "bbox_y0": f"{y0/full_height:.9f}",
                    "bbox_x1": "1.0",
                    "bbox_y1": f"{y1/full_height:.9f}",
                    "render_dpi": HISTORICAL_RENDER_DPI,
                    "processing_profile": (
                        "grayscale;autocontrast;contrast2.0;sharpness1.7"
                    ),
                    "provenance_status": "pixel_exact_parent_to_band_replay",
                    "qa_disposition": (
                        "used_in_source_repair_not_translation_certification"
                    ),
                    "parent_scan_sha256": PARENT_SHA256,
                }
            )

    for index in range(START_INDEX, END_INDEX + 1):
        script = script_dir / f"cve0p{index}.py"
        if not script.is_file():
            errors.append(f"missing cold-reverify generator: {script.name}")
            continue
        script_text = script.read_text(
            encoding="utf-8-sig", errors="replace"
        )
        if BASE.script_page_index(script_text) != index:
            errors.append(f"cold generator page mismatch: {script.name}")
        for tag, bbox in COLD_BBOXES.items():
            name = f"cve0p{index}_{tag}.png"
            path = scratch_dir / name
            if not path.is_file():
                continue
            meta = png_metadata(path)
            blocked_rows.append(
                {
                    "source_phase": "2026-07-24_cold_reverify",
                    "source_basename": name,
                    "bytes": path.stat().st_size,
                    "sha256": sha256(path),
                    "width_px": meta["width_px"],
                    "height_px": meta["height_px"],
                    "color_mode": meta["color_mode"],
                    "embedded_dpi_x": meta["embedded_dpi_x"],
                    "embedded_dpi_y": meta["embedded_dpi_y"],
                    "modified_utc": utc_mtime(path),
                    "category": "routine_page_band_derivative",
                    "public_disposition": "rights_blocked_not_public",
                    "parent_pdf_index_0based": index,
                    "parent_pdf_page_1based": index + 1,
                    "printed_page": index - PRINTED_OFFSET,
                    "linked_tex_object": "sga6_fr_workpass.tex",
                    "original_audit_entry": original_audit[index][
                        "audit_entry_number"
                    ],
                    "cold_reverify_audit_entry": cold_audit[index][
                        "audit_entry_number"
                    ],
                    "generator_basename": script.name,
                    "generator_sha256": sha256(script),
                    "generator_modified_utc": utc_mtime(script),
                    "bbox_coordinate_system": "fraction_of_parent_page",
                    "bbox_x0": bbox[0],
                    "bbox_y0": bbox[1],
                    "bbox_x1": bbox[2],
                    "bbox_y1": bbox[3],
                    "render_dpi": 2400,
                    "processing_profile": (
                        "grayscale;autocontrast;contrast1.9;sharpness1.6"
                    ),
                    "provenance_status": "exact_generator_output_recovered",
                    "qa_disposition": (
                        "used_in_cold_reverify_not_translation_certification"
                    ),
                    "parent_scan_sha256": PARENT_SHA256,
                }
            )
    blocked_rows.sort(
        key=lambda row: (
            int(row["parent_pdf_index_0based"]),
            str(row["source_phase"]),
            str(row["source_basename"]),
        )
    )
    if len(blocked_rows) != 80:
        errors.append(f"rights-blocked band count is {len(blocked_rows)}, expected 80")

    target_manifest = output_dir / TARGET_MANIFEST_NAME
    blocked_manifest = output_dir / BLOCKED_MANIFEST_NAME
    audit_context = output_dir / AUDIT_CONTEXT_NAME
    write_csv(
        target_manifest,
        target_rows,
        list(target_rows[0].keys()) if target_rows else [],
    )
    write_csv(
        blocked_manifest,
        blocked_rows,
        list(blocked_rows[0].keys()) if blocked_rows else [],
    )
    write_csv(
        audit_context,
        audit_rows,
        [
            "audit_entry_number",
            "parent_pdf_index_0based",
            "parent_pdf_page_1based",
            "printed_page_from_audit",
            "audit_heading",
        ],
    )

    with fitz.open(parent_pdf) as document:
        parent_metadata = document.metadata
        parent_pages = document.page_count
    parent_identity = {
        "title": "Theorie des intersections et theoreme de Riemann-Roch",
        "series_context": "SGA 6 source-audit parent reader",
        "source_file_basename": parent_pdf.name,
        "bytes": parent_pdf.stat().st_size,
        "sha256": PARENT_SHA256,
        "pages": parent_pages,
        "pdf_metadata": parent_metadata,
        "rotation": 0,
        "parent_scan_not_duplicated_in_this_release": True,
        "rights_status": (
            "Underlying French work and scan rights remain with their holders. "
            "No blanket license or rights transfer is asserted."
        ),
        "crop_publication_policy": (
            "Only 25 tight scholarly symbol/formula verification crops are "
            "included. Eighty historical/current full-width page-band "
            "derivatives are hash-manifested as rights-blocked; their pixels "
            "are not redistributed."
        ),
        "render_resolution_caveat": (
            "Render DPI and later Lanczos upsampling describe computational "
            "rasterization, not new optical detail beyond the parent scan."
        ),
        "cert_log_basename": cert_log.name,
        "cert_log_bytes_at_packaging_snapshot": len(cert_bytes),
        "cert_log_sha256_at_packaging_snapshot": cert_sha,
        "represented_parent_pdf_indices": {
            "distinct_indices": END_INDEX - START_INDEX + 1,
            "minimum_index_0based": START_INDEX,
            "maximum_index_0based": END_INDEX,
            "continuous_source_translation_coverage_claimed": False,
        },
    }
    parent_path = output_dir / PARENT_NAME
    write_text(
        parent_path,
        json.dumps(parent_identity, indent=2, ensure_ascii=True) + "\n",
    )

    counts_by_index: dict[int, int] = defaultdict(int)
    for row in target_rows:
        counts_by_index[int(row["parent_pdf_index_0based"])] += 1
    counts_text = ", ".join(
        f"idx{index}: {counts_by_index[index]}"
        for index in sorted(counts_by_index)
    )
    readme = f"""# SGA6 targeted high-detail source-audit crop backfill, indices 354-361

This no-overwrite release closes a visual-evidence gap in the first SGA6 crop
snapshot. It preserves 25 tight formula, glyph, punctuation, and notation crops
that were generated and read during the 2026-07-10 source repair but were not
represented by basename or SHA-256 in the earlier public targeted manifests.

## Public image archive

- `{TARGET_ZIP}` contains {len(target_rows)} targeted images /
  {sum(int(row['bytes']) for row in target_rows):,} image bytes.
- Per-index image counts: {counts_text}.
- Each target is bound through its exact generator script or inline-command
  hash to an exact rights-blocked 500-dpi source band, then to parent PDF index,
  one-based PDF page, printed page, parent scan hash, crop coordinates, scale,
  original repair ledger entry, and later cold-reverification ledger entry.
- Pixel replay is exact from parent PDF to the historical source bands and from
  those bands to all 25 published targets.

These crops cover dense lambda-ring and Chern-ring notation around formulas
(5.5.2), (5.6.1), (6.1.1), (6.1.2), (6.2.1), and (6.3.1)-(6.3.2), including
subscripts, operation symbols, punctuation, and displayed morphisms. Filenames
are historical working names; the manifest is the controlling locator.

## Rights-blocked page bands

`{BLOCKED_MANIFEST_NAME}` records {len(blocked_rows)} full-width page-band
derivatives / {sum(int(row['bytes']) for row in blocked_rows):,} bytes:

- 40 historical 500-dpi repair bands (`p354`-`p361`);
- 40 current 2400-dpi cold-reverification bands (`cve0p354`-`cve0p361`).

Their exact hashes, dimensions, page mappings, bounding boxes, generator
identities, and QA dispositions remain public, but their pixels are not
redistributed. `{METADATA_ZIP}` groups this complete provenance surface.

## Parent, claims, and rights

The parent is the 720-page Internet Archive-derived SGA6 reader
`{parent_pdf.name}`, {parent_pdf.stat().st_size:,} bytes, SHA-256
`{PARENT_SHA256}`. The parent PDF is not bundled.

These images are visual/provenance evidence used in source checking. They do
not certify the French transcription, English translation, mathematics,
completeness, or critical-edition status. Underlying French work and scan
rights remain with their holders. No blanket license or rights transfer is
asserted.
"""
    readme_path = output_dir / README_NAME
    write_text(readme_path, readme)

    metadata_paths = [
        readme_path,
        parent_path,
        target_manifest,
        blocked_manifest,
        audit_context,
    ]
    metadata_privacy: dict[str, list[str]] = {}
    for path in metadata_paths:
        hits = privacy_hits(
            [path.read_text(encoding="utf-8", errors="replace")]
        )
        if hits:
            metadata_privacy[path.name] = hits
    if metadata_privacy:
        errors.append(f"generated metadata privacy hits: {metadata_privacy}")

    csv_formula_triggers = {
        path.name: formula_triggers(path)
        for path in (target_manifest, blocked_manifest, audit_context)
    }
    for name, triggers in csv_formula_triggers.items():
        if triggers:
            errors.append(f"formula-trigger cells in {name}: {triggers}")

    target_zip_path = zip_dir / TARGET_ZIP
    metadata_zip_path = zip_dir / METADATA_ZIP
    target_zip_result = zip_payload(
        target_zip_path,
        target_rows,
        scratch_dir,
        [readme_path, parent_path, target_manifest, audit_context],
    )
    metadata_zip_result = zip_payload(
        metadata_zip_path,
        [],
        scratch_dir,
        metadata_paths,
    )
    errors.extend(str(error) for error in target_zip_result["errors"])
    errors.extend(str(error) for error in metadata_zip_result["errors"])

    race_errors: list[str] = []
    for name, initial in initial_files.items():
        path = scratch_dir / name
        if not path.is_file():
            race_errors.append(f"source disappeared during freeze: {name}")
            continue
        stat = path.stat()
        current = (stat.st_size, stat.st_mtime_ns, sha256(path))
        if current != initial:
            race_errors.append(f"source changed during freeze: {name}")
    errors.extend(race_errors)

    validation = {
        "schema": "sga6_targeted_crop_backfill_idx354_361_validation_v1",
        "status": "PASS" if not errors else "FAIL",
        "errors": errors,
        "selection": {
            "targeted_public_images": len(target_rows),
            "targeted_public_bytes": sum(
                int(row["bytes"]) for row in target_rows
            ),
            "rights_blocked_page_bands": len(blocked_rows),
            "rights_blocked_page_band_bytes": sum(
                int(row["bytes"]) for row in blocked_rows
            ),
            "historical_rights_blocked_bands": sum(
                row["source_phase"] == "2026-07-10_source_repair"
                for row in blocked_rows
            ),
            "cold_reverify_rights_blocked_bands": sum(
                row["source_phase"] == "2026-07-24_cold_reverify"
                for row in blocked_rows
            ),
            "parent_indices": list(range(START_INDEX, END_INDEX + 1)),
        },
        "deduplication": {
            "prior_target_manifest_hashes": len(previous_hashes),
            "target_hash_intersection": sorted(
                target_hashes_seen & previous_hashes
            ),
        },
        "pixel_replay": {
            "parent_to_historical_band_files": len(historical_band_meta),
            "parent_to_historical_band_errors": historical_replay_errors,
            "historical_band_to_target_files": len(target_rows),
            "historical_band_to_target_errors": target_replay_errors,
        },
        "parent_source": parent_identity,
        "audit_context": {
            "rows": len(audit_rows),
            "original_entries": len(original_audit),
            "cold_reverify_entries": len(cold_audit),
            "sha256": sha256(audit_context),
        },
        "csv_formula_safety": csv_formula_triggers,
        "metadata_privacy": {
            "files_scanned": len(metadata_paths),
            "hits": metadata_privacy,
        },
        "freeze_race_recheck": {
            "files": len(initial_files),
            "errors": race_errors,
        },
        "zip_validation": {
            TARGET_ZIP: target_zip_result,
            METADATA_ZIP: metadata_zip_result,
        },
    }
    validation_path = output_dir / VALIDATION_NAME
    write_text(
        validation_path,
        json.dumps(validation, indent=2, ensure_ascii=True) + "\n",
    )

    upload_rows = [
        {
            "filename": target_zip_path.name,
            "bytes": target_zip_path.stat().st_size,
            "sha256": sha256(target_zip_path),
            "role": "targeted_image_archive",
            "status": "proposed_public",
        },
        {
            "filename": metadata_zip_path.name,
            "bytes": metadata_zip_path.stat().st_size,
            "sha256": sha256(metadata_zip_path),
            "role": "provenance_and_rights_blocked_metadata_archive",
            "status": "proposed_public",
        },
    ]
    upload_manifest = output_dir / UPLOAD_MANIFEST_NAME
    write_csv(
        upload_manifest,
        upload_rows,
        ["filename", "bytes", "sha256", "role", "status"],
    )
    sha_path = output_dir / SHA_NAME
    checksum_paths = metadata_paths + [validation_path, upload_manifest]
    write_text(
        sha_path,
        "".join(
            f"{sha256(path)}  {path.name}\n"
            for path in sorted(checksum_paths, key=lambda p: p.name.lower())
        ),
    )

    final_status = "PASS" if not errors else "FAIL"
    print(
        json.dumps(
            {
                "status": final_status,
                "targeted_images": len(target_rows),
                "rights_blocked_bands": len(blocked_rows),
                "target_zip": target_zip_result,
                "metadata_zip": metadata_zip_result,
                "validation_sha256": sha256(validation_path),
                "upload_manifest_sha256": sha256(upload_manifest),
                "sha256sums_sha256": sha256(sha_path),
            },
            indent=2,
        )
    )
    return 0 if final_status == "PASS" else 1


if __name__ == "__main__":
    sys.exit(main())
