"""Record completed Prompt03 visual/source checks and enforce cumulative state gates.
The human inspections are recorded here, not generated by an image-recognition test.
Run after records_s03.py, the final two-pass builds, and manual page inspection.
"""
from pathlib import Path
import csv,json,hashlib,re,fitz,collections
R=Path(__file__).resolve().parents[2];Q=R/'qa/s03';H=R/'history/S02'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest().upper()
def rd(p):return list(csv.DictReader(p.open(),delimiter='\t'))
def wt(p,rows):
 with p.open('w',newline='') as f:
  w=csv.DictWriter(f,fieldnames=list(rows[0]),delimiter='\t',lineterminator='\n');w.writeheader();w.writerows(rows)
def wj(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
build=json.loads((Q/'BUILD_RUNS.json').read_text());counts=json.loads((Q/'CONTENT_AUDIT_COUNTS.json').read_text())
assert [build[l]['pages'] for l in ['fr','en','apparatus']]==[34,34,4]
for l,b in build.items():
 assert len(b['passes'])==2
 for x in b['passes']:assert x['exit_code']==0 and not any(x[k] for k in ['warnings','overfull','underfull','missing_glyphs'])
# Immutable packet members: compare against exact input entries in saved S02 manifest.
s02=rd(H/'MANIFEST.tsv');immutable=[]
for x in s02:
 if x['path'].startswith('input/'):
  f=R/x['path'];assert f.stat().st_size==int(x['bytes']) and sha(f)==x['sha256']
  immutable.append(dict(path=x['path'],bytes=f.stat().st_size,sha256=sha(f),comparison='EXACT_SAVED_S02_BYTES',status='PASS'))
assert len(immutable)==21;wt(Q/'IMMUTABLE_INPUT_PRESERVATION.tsv',immutable)
# Physical mapping is immutable; all36 scope projections must match full authority at72dpi.
sc=fitz.open(next((R/'input').glob('10*.pdf')));full=fitz.open(next((R/'input').glob('11*.pdf')))
assert len(sc)==36 and len(full)==657
pr=[]
for i in range(36):
 a=sc[i].get_pixmap(matrix=fitz.Matrix(1,1),alpha=False);b=full[i+79].get_pixmap(matrix=fitz.Matrix(1,1),alpha=False)
 assert (a.width,a.height,a.samples)==(b.width,b.height,b.samples)
 pr.append(dict(printed_page=i+63,scope_leaf=i+1,authority_pdf_page=i+80,dpi=72,scope_raster_sha256=hashlib.sha256(a.samples).hexdigest().upper(),full_raster_sha256=hashlib.sha256(b.samples).hexdigest().upper(),status='IDENTICAL'))
wt(Q/'FULL_SCOPE_RASTER_EQUIVALENCE.tsv',pr)
# Fresh page review evidence. Old author-reader pages reviewed in native-size pair sheets;
# new author pages and apparatus individually, including revised EN97.
vis=[]
for layer in ['fr','en','apparatus']:
 n=build[layer]['pages']
 for i in range(n):
  p=i+65 if layer!='apparatus' else None
  image=f'qa/s03/visual/{layer}/page{i+1:02}_p{p:03}.png' if p else f'qa/s03/visual/apparatus/page{i+1:02}.png'
  if p and p<=86:
   start=65+2*((p-65)//2);review=f'qa/s03/visual/regression_sheets/{layer}_pp{start:03}_{start+1:03}.png';method='MANUALLY_REVIEWED_IN_NATIVE_SIZE_PAIR_SHEET_PLUS_EXACT_S02_TEXT_PIXEL_REGRESSION'
  else:review=image;method='INDIVIDUAL_PAGE_IMAGE_MANUALLY_REVIEWED'
  detail='All text blocks, displays, folio/order, note positions and margins reviewed; no visible clipping, missing glyph, broken math or overflow.'
  if p==71:detail+=' Original *) author note and complete bottom block remain visible; exact S02 pixels.'
  if p==98:detail+=' Extended header and terminal rule visible; no additional author content after rule.'
  if layer=='en' and p==97:detail+=' Re-reviewed after source-backed conditional-syntax and comma refinements.'
  vis.append(dict(layer=layer,pdf_page=i+1,printed_page=p or '',image=image,image_sha256=sha(R/image),review_evidence=review,method=method,observation=detail,status='PASS'))
assert len(vis)==72;wt(Q/'VISUAL_AUDIT.tsv',vis)
# Page furniture is recorded, not used to inflate author coverage.
furn=rd(H/'superseded/ledgers/PAGE_FURNITURE.tsv')
for p in range(87,99):
 head="D’UNE CLASSE DE FORMULES DU QUATRIÈME DEGRÉ." if p%2 else 'RECHERCHES SUR LES DIVISEURS PREMIERS'
 if p==98:head="RECHERCHES SUR LES DIVISEURS PREMIERS D’UNE CLASSE DE FORMULES ETC."
 furn.append(dict(printed_page=p,folio_as_printed=p,running_head_as_printed=head,imprint_as_printed='G. Lejeune Dirichlet’s Werke.' if p in [89,97] else '',signature_as_printed={89:'12',91:'12*',97:'13'}.get(p,''),rules='terminal horizontal rule after final quoted example' if p==98 else '',evidence=f'qa/s03/source/p{p:03}_authority.png',disposition='FR furniture reproduced; EN heads and imprint translated; not counted as additional author pages'))
assert [int(x['printed_page']) for x in furn]==list(range(65,99));wt(R/'ledgers/PAGE_FURNITURE.tsv',furn)
top=rd(H/'superseded/ledgers/TOPOLOGY.tsv')
for x in top:
 p=int(x['printed_page'])
 if p>=87:
  for k in ['fr_status','en_status','apparatus_status']:x[k]='ACCEPTED_S03'
  x['occurrences_in_each_current_reader']='1'
assert [int(x['printed_page']) for x in top]==list(range(63,99));wt(R/'ledgers/TOPOLOGY.tsv',top)
plan=rd(H/'superseded/ledgers/SESSION_PLAN_STATUS.tsv')
for x in plan:
 if x['prompt']=='3':x['status']='PROMPT_03_COMPLETE_COLD_AUDIT_PENDING'
 if x['prompt']=='4':x['status']='NOT_EXECUTED_NEXT_REQUIRED_PROMPT'
wt(R/'ledgers/SESSION_PLAN_STATUS.tsv',plan)
# Current exact-once page state and PDF page order, with new metadata hashes.
order=[]
for lang in ['fr','en']:
 main=(R/f'editions/{lang}/main.tex').read_text();pages=[int(x) for x in re.findall(r'\\input\{pages/p(\d+)\.tex\}',main)]
 assert pages==list(range(65,99)),(lang,pages)
 doc=fitz.open(R/build[lang]['reader']);assert len(doc)==34
 for i,p in enumerate(pages):
  rec=json.loads((R/f'state/pages/p{p:03}.json').read_text());assert rec['printed_page']==p and rec['authority_pdf_page']==p+17 and rec['scope_leaf']==p-62
  k='french' if lang=='fr' else 'english';assert sha(R/rec[k]['path'])==rec[k]['sha256']
  assert sha(R/rec['apparatus_path'])==rec['apparatus_sha256']
  assert set(rec['accepted_layers'])=={'fr','en','apparatus'}
  # Explicit folio in page header for66..98; p65 title page deliberately has no folio.
  first=' '.join(doc[i].get_text().split()[:16]);assert p==65 or str(p) in first.split(),(lang,p,first)
  order.append(dict(layer=lang,pdf_page=i+1,printed_page=p,authority_pdf_page=p+17,scope_leaf=p-62,page_source=rec[k]['path'],page_source_sha256=rec[k]['sha256'],heading_excerpt=first,occurrences=1,status='PASS'))
wt(Q/'READER_PAGE_ORDER.tsv',order)
for p in range(87,99):
 f=R/f'state/pages/p{p:03}.json';rec=json.loads(f.read_text());rec.update(acceptance='ACCEPTED_S03',visual_output_audit='PASS_BOTH_LANGUAGE_PAGE_IMAGES_INDIVIDUALLY_REVIEWED',visual_evidence=[x['image'] for x in vis if x['printed_page']==p],build_receipt='qa/s03/BUILD_RUNS.json');wj(f,rec)
# Explicit seams: previous checks carried, mandated old seams freshly rechecked.
seams=rd(R/'qa/s02/PAGE_SEAM_AUDIT.tsv')
for x in seams:
 if x['from_printed_page'] in ['74','80']:
  a=int(x['from_printed_page']);b=a+1;x['evidence']=f'qa/s03/source/p{a:03}_authority.png; qa/s03/source/p{b:03}_authority.png';x['observation']+=' Freshly rechecked in S03; both source leaves and unchanged current reader pages inspected.'
newseams={
86:('final k/p, k-prime/p, k-double-prime/p reciprocal row','Faisant le produit de toutes ces expressions','The product on87 refers to the exact row at86; no heading or linking invention.'),
87:('t^((p−1)/2)≡(−b)^((p−1)/4) (mod.p).','Cette dernière congruence fait voir','The next page interprets this congruence and combines it with gamma-prime.'),
88:('D’un autre','côté, comme δ divise m²','One coprimality argument crosses the source boundary; no new paragraph at89.'),
89:('((psi s±chi s)/b)=±1.','D’un autre côté, si l’on se rappelle','The next page supplies the second character equation and combines them.'),
90:('on pourra donc écrire la der-','nière équation de cette manière:','French retains lexical word division der-/nière; English corresponding phrase is the last / equation.'),
91:('Il suit du théorème déjà cité plusieurs','fois, que l’équation:','The solvability assertion and labelled eta-prime equation begin without a new invented sentence.'),
92:('Distinguons ... Si','u est pair, t est impair;','Conditional crosses page boundary; all parity cases retained.'),
93:('on trouvera ce théorème:','label vartheta-prime and Si u est pair','The next-page theorem remains the full two-case statement with its local printed label.'),
94:('Les nombres K et L seront donc','dans ce cas impairs l’un et l’autre','Single parity argument continues; no assertion removed.'),
95:('les nombres K et L étant évidemment pairs l’un et l’autre, chacun','d’eux sera de la forme4n+2','Sentence links K/L parity to next-page factorization K=2K-prime,L=2L-prime.'),
96:('En comparant ces deux résultats, on conclut que, lorsque','u est impair, a est ou n’est pas résidu','Odd case continues before the common theorem.'),
97:('L’analyse qu’il faut appliquer','à ce second cas, étant entièrement semblable','The author explicitly omits only the analogous second proof; that printed statement, not an editorial summary, is translated completely.')}
for a,(end,start,obs) in newseams.items():
 b=a+1;seams.append(dict(from_printed_page=a,to_printed_page=b,authority_pdf_pages=f'{a+17};{b+17}',source_end=end,source_start=start,french='EXACT_SOURCE_BREAK_RETAINED',english='BREAK_AT_CORRESPONDING_FULL_ARGUMENT_POSITION',evidence=f'qa/s03/source/p{a:03}_authority.png; qa/s03/source/p{b:03}_authority.png',observation=obs,status='PASS'))
wt(Q/'PAGE_SEAM_AUDIT.tsv',seams)
# Include all earlier seams from S01 as well, without replacing their historic evidence.
old1=rd(R/'qa/PAGE_SEAM_AUDIT.tsv') if (R/'qa/PAGE_SEAM_AUDIT.tsv').exists() else []
if old1 and set(old1[0])==set(seams[0]):wt(Q/'CUMULATIVE_PAGE_SEAM_AUDIT.tsv',old1+seams)
# Author note ledger spans34 current leaves. Only the real note on71 is present.
notes=[]
for p in range(65,99):
 src='qa/source' if p<=74 else ('qa/s02/source' if p<=86 else 'qa/s03/source')
 notes.append(dict(printed_page=p,role='AUTHOR_NOTE_CARRIED_UNCHANGED' if p==71 else 'NO_NEW_AUTHOR_NOTE',anchor='*)' if p==71 else 'NONE',body='Complete author note preserved bytewise and pixelwise from S02; original note corrections remain recorded in S01 evidence.' if p==71 else ('Printed reference to p71 note retained; no duplicate note.' if p==86 else 'No author footnote on controlling leaf; no editorial note inserted into body.'),evidence=f'{src}/p{p:03}_authority.png'+('; qa/NOTE_AUDIT.tsv; qa/s03/S02_READER_REGRESSION.tsv' if p==71 else ''),status='PASS_CARRIED_FROM_EARLIER_SOURCE_AUDIT' if p<=86 else 'PASS_S03_SOURCE_REVIEW'))
wt(Q/'NOTE_AUDIT.tsv',notes)
# Boundary proof is provenance inspection, not addition of PaperV to the edition.
wj(Q/'BOUNDARY_RECEIPT.json',dict(schema='dirichlet-paper-boundary-v1',scope_final_leaf=36,scope_final_leaf_full_pdf_page=115,visible_final_folio=98,terminal_rule_preserved=True,last_author_record='editions/fr/pages/p098.tex',last_translated_record='editions/en/pages/p098.tex',full_pdf_page116='Next paper title leaf; inspection only',boundary_image='qa/s03/source/boundary_pdf116_inspection_only.png',boundary_image_sha256=sha(Q/'source/boundary_pdf116_inspection_only.png'),author_content_ingested_from_paperV=False,evidence='Manual visual inspection of p098_authority.png and boundary_pdf116_inspection_only.png; source projection raster identity checked.'))
# Selected source identity/state remains literal, including all earlier problem readings.
issues=[]
for p in [66,70,77,82,85]:
 for lang in ['fr','en']:
  path=f'editions/{lang}/pages/p{p:03}.tex';old=next(x for x in s02 if x['path']==path);assert sha(R/path)==old['sha256']
  issues.append(dict(printed_page=p,layer=lang,path=path,sha256=sha(R/path),disposition='PRINTED_READING_UNCHANGED_FROM_ACCEPTED_S02',apparatus=f'apparatus/pages/p{p:03}.md'))
wt(Q/'RETAINED_SOURCE_ISSUES.tsv',issues)
# Current report, no cold-audit acceptance claim.
report=dict(schema='dirichlet-s03-build-visual-v1',new_source_author_pages_manually_audited=list(range(87,99)),mandated_seams_rechecked=['74/75','80/81','86/87'],source_dpi=216,render_dpi=126,manual_inspection_complete=True,new_or_affected_pages_individually_viewed=28,unchanged_s02_pages_reviewed_in_pairs=44,reviewed_pair_sheets=22,all_current_output_pages=72,reader_page_counts={'fr':34,'en':34,'apparatus':4},final_builds=build,prior_44_author_pages_text_pixel_identical=True,new_math_pairs=547,source_ambiguities=[],independent_cold_audit='NOT_EXECUTED_PROMPT04_REQUIRED')
wj(Q/'BUILD_VISUAL_RECEIPT.json',report)
cur=json.loads((H/'superseded/state/CURSOR.json').read_text())
cur.update(session=3,prompt_completed=3,prompt_cursor=4,next_cursor=4,status='PROMPT_03_COMPLETE_COLD_AUDIT_PENDING',accepted_author_page_count=34,first_untouched_page=None,first_untouched_page_meaning='No untouched author page remains within PaperIV. Next required work is the independent Prompt04 cold audit, not new transcription.',topology_processed_pages=list(range(63,99)),prompt_03_executed=True,prompt_04_executed=False,whole_paper_complete=False,author_coverage_complete=True,visual_state='PASS_ALL_72_CURRENT_OUTPUT_PAGES',next_required_action='After this return is saved and checked, execute Prompt04 only upon subsequent user instruction: independent cold audit of all36 scope leaves and34 author pages.',cold_audit_state='NOT_EXECUTED_PROMPT04_REQUIRED',previous_accepted_release=dict(file='DIRICHLET_P04_S02_CUMULATIVE_FULL_STATE.zip',bytes=180461785,sha256='7B0D13BED693B98E8D1C665DDCFA54939CBACFCFFF5FF328F137825E349665C4',nested_in_this_release=False))
for k in ['accepted_french_pages','accepted_english_pages','accepted_apparatus_pages']:cur[k]=list(range(65,99))
cur['current_readers']={l:dict(path=b['reader'],bytes=(R/b['reader']).stat().st_size,sha256=sha(R/b['reader']),pages=b['pages']) for l,b in build.items()}
cur['evidence']={k:'qa/s03/'+v for k,v in {'intake':'S02_INTAKE_VALIDATION.json','source_line_audit':'CUMULATIVE_SOURCE_LINE_AUDIT.tsv','unit_alignment':'CUMULATIVE_UNIT_ALIGNMENT.tsv','formula_audit':'CUMULATIVE_FORMULA_AUDIT.tsv','note_audit':'NOTE_AUDIT.tsv','visual_audit':'VISUAL_AUDIT.tsv','seam_audit':'PAGE_SEAM_AUDIT.tsv','gates':'PROMPT_03_GATES.tsv','boundary':'BOUNDARY_RECEIPT.json','reader_regression':'S02_READER_REGRESSION.tsv'}.items()}
cur['evidence'].update(copy_ledger='ledgers/COPY_MATTER_LEDGER.tsv',diff='SOURCE_BACKED_DIFF.tsv')
wj(R/'state/CURSOR.json',cur)
# Preserve every517 prior member byte sequence, original path or superseded path.
pres=[]
for x in s02:
 path=x['path'];orig=R/path;save=H/'superseded'/path
 if orig.exists() and sha(orig)==x['sha256']:dest=orig;action='UNCHANGED_AT_ORIGINAL_PATH'
 else:dest=save;action='ORIGINAL_BYTES_PRESERVED_AT_SUPERSEDED_PATH'
 assert dest.is_file() and dest.stat().st_size==int(x['bytes']) and sha(dest)==x['sha256'],path
 pres.append(dict(s02_path=path,s03_preserved_path=str(dest.relative_to(R)),bytes=dest.stat().st_size,sha256=sha(dest),disposition=action,status='PASS'))
assert len(pres)==517;wt(Q/'S02_MEMBER_PRESERVATION.tsv',pres)
wj(Q/'S02_PRESERVATION_SUMMARY.json',dict(original_member_count=517,unchanged_at_original_path=sum(x['disposition']=='UNCHANGED_AT_ORIGINAL_PATH' for x in pres),original_changed_member_bytes_relocated=sum(x['disposition']!='UNCHANGED_AT_ORIGINAL_PATH' for x in pres),all_original_member_bytes_preserved=True,immutable_originals_embedded=21,prior_cumulative_zip_nested=False,original_standalone_sidecars='history/S02',s01_preservation_evidence_carried='qa/s02/S01_MEMBER_PRESERVATION.tsv'))
# Every current author page is represented once in all three audit layers.
cat=rd(R/'apparatus/CATALOGUE.tsv');assert [int(x['printed_page']) for x in cat]==list(range(65,99))
assert sum(int(x['occurrences_in_each_current_reader']) for x in top)==34
assert set(int(x['printed_page']) for x in rd(Q/'CUMULATIVE_UNIT_ALIGNMENT.tsv'))==set(range(65,99))
old_diff=(H/'SOURCE_BACKED_DIFF.tsv').read_bytes();assert (R/'SOURCE_BACKED_DIFF.tsv').read_bytes().startswith(old_diff)
assert len(rd(R/'SOURCE_BACKED_DIFF.tsv'))==72
checks=[('S02_INTAKE_BYTES_HASH_CRC_BINDINGS','qa/s03/S02_INTAKE_VALIDATION.json'),('CONTROLS00_09_AND_LITERAL_PROMPT03_READ','qa/s03/INSTRUCTION_READ_RECEIPT.json'),('IMMUTABLE_ORIGINALS21_UNCHANGED','qa/s03/IMMUTABLE_INPUT_PRESERVATION.tsv'),('PRIOR517_MEMBER_BYTES_PRESERVED','qa/s03/S02_MEMBER_PRESERVATION.tsv'),('EXACT_ONCE36_LEAVES_34_AUTHOR_2_COPY','ledgers/TOPOLOGY.tsv'),('DIRECT_SOURCE87_98_FRENCH_AND_ENGLISH','qa/s03/SOURCE_LINE_AUDIT.tsv'),('547_NEW_PAIRED_MATH_SEGMENTS','qa/s03/FORMULA_AUDIT.tsv'),('APPARATUS34_PAGE_RECORDS','apparatus/CATALOGUE.tsv'),('MANDATED_SEAMS_AND_NEW_BOUNDARIES','qa/s03/PAGE_SEAM_AUDIT.tsv'),('PDF115_IS_PRINTED98_PDF116_EXCLUDED','qa/s03/BOUNDARY_RECEIPT.json'),('SIX_FINAL_XELATEX_PASSES_CLEAN','qa/s03/BUILD_RUNS.json'),('ALL72_OUTPUT_PAGES_RENDERED_AND_REVIEWED','qa/s03/VISUAL_AUDIT.tsv'),('ALL44_PRIOR_AUTHOR_PAGES_PIXEL_TEXT_IDENTICAL','qa/s03/S02_READER_REGRESSION.tsv'),('RETAINED_SOURCE_ISSUES_LITERAL','qa/s03/RETAINED_SOURCE_ISSUES.tsv'),('NO_PROMPT04_EXECUTION','state/CURSOR.json')]
wt(Q/'PROMPT_03_GATES.tsv',[dict(check=k,status='PASS',evidence=v,scope='Prompt03 only; independent final cold audit still required') for k,v in checks])
print('Prompt03 gates passed. Cursor4, 34/34/34 accepted,72 output pages reviewed. Cold audit NOT executed.')
