$ErrorActionPreference = 'Stop'
$jsonlPath = Join-Path $PSScriptRoot 'difficulty_ledger.jsonl'
$csvPath = Join-Path $PSScriptRoot 'difficulty_ledger.csv'
if ((Test-Path -LiteralPath $jsonlPath) -or (Test-Path -LiteralPath $csvPath)) { throw 'Append-only Paper 3 difficulty ledger already exists.' }

$authorityPath = '${PUBLIC_INTERLANGUAGE_ROOT}/03_projects/noether/07_german_canon_control/candidates/NOETH-DE-ED-0001/Noether_German_NOETH-DE-ED-0001.tex'
$authoritySha = 'D1F06B311F6CBD991DD247D745DD9A72DDE326A20396DF43CFE0C8EDB1593CDB'
$choicesPath = '${PUBLIC_INTERLANGUAGE_ROOT}/03_projects/language_management/cjk/03_working_translations/noether_paper03_ko_translation_001_20260804/TRANSLATION_CHOICES_U01_U03.md'
$choicesSha = '3299C07345D907C6FA387EBB2B18A7E656EF95A6181F4D38EC07EED402ED4AB3'
$targetRoot = '${PUBLIC_INTERLANGUAGE_ROOT}/03_projects/language_management/cjk/03_working_translations/noether_paper03_ko_translation_001_20260804/targets'
$unitSourceHashes = [ordered]@{U01='DF50EAD7065F663901F51ADFCA37A138921063362CA449665D37B855921B496C';U02='A7B7CA981F7B8D6B32171BF0709E27440A25B2754642BD095304E54A5A25D5C6';U03='0D110465AEE20E18EE1427577D33D435FCF97D5CA99BEF3878EF52DC341F01A5'}
$targetHashes = [ordered]@{U01='057D6EAECAAB02C4D19C6908276C11E32953748726BD36B628712AB5C5E78ECB';U02='A2A9F68B55C15EEFEAE178B4F24CB5D56222E563F6B5A126F46D1AA75BEA38B1';U03='7942126177C707C89F67444BE020F90F2139C0C5036A153297C0A7F83119F4B4'}

function New-Targets([string[]]$UnitIds) {
    $items=@()
    foreach($unit in $UnitIds){
        $items += [ordered]@{artifact_id=$unit;path="$targetRoot/Noether_P03_Korean_$($unit)_UNCHECKED.tex";sha256=$targetHashes[$unit];hash_state='frozen_producer_identity'}
    }
    return @($items)
}

$lines=[System.Collections.Generic.List[string]]::new()
$csvRows=[System.Collections.Generic.List[object]]::new()
$script:previous=$null
$script:sequence=0

function Add-Record {
    param([string]$Category,[string[]]$UnitIds,[string[]]$Locators,[string]$SenseWindow,[string[]]$FactClasses,[string]$Symptom,[object[]]$CauseEvidence,[object[]]$Attempts,[string[]]$Rejected,[string]$ResolutionState,[string]$Resolution,[string]$ResidualRisk,[string[]]$RecurrenceCues,[string]$DominanceRisk,[string]$LexicalBasin,[string[]]$DecisionIds,[string[]]$StructuralIds,[string]$Lesson,[string]$Revisit)
    $script:sequence++
    $recordId='CJK-KO-P03-HARD-{0:D3}' -f $script:sequence
    $record=[ordered]@{
        schema_version='1.0.0';record_id=$recordId;recorded_at='2026-08-04';time_precision='day';append_sequence=$script:sequence;previous_record_sha256=$script:previous;work_id='NOE-P03-KO';unit_ids=@($UnitIds)
        authority=[ordered]@{path=$authorityPath;snapshot_sha256=$authoritySha;historical_whole_source_sha256=$authoritySha;locators=@($Locators);unit_slice_sha256=$unitSourceHashes}
        targets=@(New-Targets $UnitIds);category=$Category;sense_window=$SenseWindow;fact_classes=@($FactClasses);symptom=$Symptom;cause_evidence=@($CauseEvidence);attempted_approaches=@($Attempts);rejected_approaches=@($Rejected);resolution_state=$ResolutionState;resolution=$Resolution
        evidence=@([ordered]@{kind='producer_choices';detail='Frozen producer choices and adverse sense windows.';path=$choicesPath;sha256=$choicesSha})
        residual_risk=$ResidualRisk;recurrence_cues=@($RecurrenceCues);mandarin_simplified_dominance_risk=$DominanceRisk;lexical_attractor_basin=$LexicalBasin;related_decision_ids=@($DecisionIds);related_structural_ids=@($StructuralIds);transferable_lesson=$Lesson;review_state='producer_metadata_unchecked';supersession_state='current';revisit_condition=$Revisit;record_sha256=$null
    }
    $placeholder=$record|ConvertTo-Json -Depth 20 -Compress
    $hash=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($placeholder)))
    $record.record_sha256=$hash
    $lines.Add(($record|ConvertTo-Json -Depth 20 -Compress))
    $script:previous=$hash
    $csvRows.Add([pscustomobject][ordered]@{record_id=$recordId;append_sequence=$script:sequence;recorded_at='2026-08-04';time_precision='day';category=$Category;unit_ids=($UnitIds -join ';');source_locators=($Locators -join ';');target_ids=($UnitIds -join ';');resolution_state=$ResolutionState;symptom=$Symptom;residual_risk=$ResidualRisk;recurrence_cues=($RecurrenceCues -join ';');related_decision_ids=($DecisionIds -join ';');related_structural_ids=($StructuralIds -join ';');revisit_condition=$Revisit;record_sha256=$hash})
}

$sf='source_fact';$comp='computation';$inf='editorial_inference';$pref='model_preference'

Add-Record -Category 'archive_release_hold' -UnitIds @('U01','U02','U03') -Locators @('Paper 3 whole-authority lines 3573-3608','controls 3609-3610 excluded') -SenseWindow 'Producer draft completion versus archive/publication eligibility.' -FactClasses @($sf,$comp) -Symptom 'Editable draft coverage and honest UNCHECKED labels can be mistaken for release readiness.' -CauseEvidence @([ordered]@{kind=$sf;detail='CJK-KO-ARCH-001 states that unchecked, uncompiled, and unrendered are honest labels, never release holds.';path=$null;sha256=$null}) -Attempts @([ordered]@{approach='Treat completed draft coverage as archive eligibility.';outcome='Rejected by controlling archive policy.';status='rejected'},[ordered]@{approach='Retain explicit release hold and route publication only through archive maintenance.';outcome='Accepted active control.';status='accepted'}) -Rejected @('Producer self-release','Package or publication inference from hashes') -ResolutionState 'active_control' -Resolution 'All P03 bytes remain private producer/checker material; archive maintenance alone owns release disposition.' -ResidualRisk 'Downstream users may confuse exact hashes or coverage with approval.' -RecurrenceCues @('archive handoff request','publication claim','unchecked presented as ready') -DominanceRisk 'not_applicable' -LexicalBasin 'not_applicable' -DecisionIds @('CJK-KO-ARCH-001') -StructuralIds @('NOE-P03-KO-WORK-001') -Lesson 'State labels describe evidence status; they never substitute for an authorized release decision.' -Revisit 'Only archive maintenance may append a release-state successor after independent checking, compilation, rendering, and its own controls.'

Add-Record -Category 'language_evidence_gap' -UnitIds @('U01','U02','U03') -Locators @('Paper 3 whole-authority lines 3573-3608') -SenseWindow 'Korean-native and ko-KP evidence versus fluent Sino-Korean model preferences.' -FactClasses @($inf,$pref) -Symptom 'No Korean-native historical invariant-theory shelf or ko-KP evidence authorized the producer lexicon or Hanja.' -CauseEvidence @([ordered]@{kind=$inf;detail='The producer choices file records missing Korean/ko-KP/Hanja evidence and qualitative Mandarin-Simplified dominance debt.';path=$choicesPath;sha256=$choicesSha}) -Attempts @([ordered]@{approach='Infer Korean authority from Chinese or Japanese cognates.';outcome='Rejected.';status='rejected'},[ordered]@{approach='Expose choices as model preferences for an independent Korean checker.';outcome='Accepted provisional control.';status='accepted'}) -Rejected @('Chinese authorizes Korean','Japanese authorizes Korean','Unverified Hanja expansion','Pan-Korean claim') -ResolutionState 'held' -Resolution 'Require Korean-language evidence and separate ko-KP evidence before regional or Hanja claims.' -ResidualRisk 'Natural-looking calques may be unattested, anachronistic, or regionally marked.' -RecurrenceCues @('Sino-xenic cognate','Hanja request','ko-KP claim','Mandarin-dominant evidence shelf') -DominanceRisk 'evidence_debt' -LexicalBasin 'unresolved' -DecisionIds @() -StructuralIds @('NOE-P03-KO-WORK-001','NOE-P03-KO-U01-UNIT-001','NOE-P03-KO-U02-UNIT-001','NOE-P03-KO-U03-UNIT-001') -Lesson 'Language-specific evidence cannot be borrowed across CJK lanes.' -Revisit 'Independent Korean and ko-KP specialists return explicit evidence.'

Add-Record -Category 'terminology' -UnitIds @('U01','U02','U03') -Locators @('lines 3574,3582,3584,3586,3596,3607') -SenseWindow 'binär, ternär, quaternär, n-är as form arity and technical domain labels.' -FactClasses @($sf,$pref) -Symptom 'U01 uses 이원/삼원 while U02 uses 3원/4원; mixed styles can obscure a single historical arity system.' -CauseEvidence @([ordered]@{kind=$pref;detail='Parallel producer units selected different Hangul/numeric surface forms.';path=$choicesPath;sha256=$choicesSha}) -Attempts @([ordered]@{approach='Silently normalize all arity labels during metadata work.';outcome='Rejected because this is checker work.';status='rejected'},[ordered]@{approach='Expose both forms and require one corpus decision.';outcome='Accepted hold.';status='accepted'}) -Rejected @('Unlogged global replacement') -ResolutionState 'held' -Resolution 'Independent checker must select and propagate one evidence-backed arity style.' -ResidualRisk 'Mixed labels can look like different mathematical scopes.' -RecurrenceCues @('binary/ternary/quaternary','Arabic numeral plus 원','Hangul numeral plus 원') -DominanceRisk 'active_qualitative_control' -LexicalBasin 'mixed/contested' -DecisionIds @() -StructuralIds @('NOE-P03-KO-U01-UNIT-001','NOE-P03-KO-U02-UNIT-001','NOE-P03-KO-U03-UNIT-001') -Lesson 'Coupled historical labels should be decided as a family, not one token at a time.' -Revisit 'Independent Korean invariant-theory checker decision.'

Add-Record -Category 'terminology' -UnitIds @('U01','U02','U03') -Locators @('lines 3574,3582,3584,3586,3590,3596,3607') -SenseWindow 'Form, Formensystem, Formenzusammenhang, and invariante Bildung in classical invariant theory.' -FactClasses @($sf,$pref) -Symptom 'Ordinary Korean meanings of 형식, 구성, and 연관 can flatten algebraic generation and relation structure.' -CauseEvidence @([ordered]@{kind=$pref;detail='Producer chose 형식, 형식계, 형식들의 연관관계, and 불변 구성식 without external Korean validation.';path=$choicesPath;sha256=$choicesSha}) -Attempts @([ordered]@{approach='Use generic everyday equivalents without a sense window.';outcome='Rejected.';status='rejected'},[ordered]@{approach='Keep the algebraic family explicit for checker review.';outcome='Accepted hold.';status='accepted'}) -Rejected @('Document-format reading of Form','Educational-formation reading of Bildung') -ResolutionState 'held' -Resolution 'Checker must bind the four terms across all three units and any corpus predecessors.' -ResidualRisk 'Local substitutions can break claims about finite systems, generation, and relations.' -RecurrenceCues @('Formensystem','Bildung','Formenzusammenhang') -DominanceRisk 'active_qualitative_control' -LexicalBasin 'modern Sino-xenic coinage/calque' -DecisionIds @() -StructuralIds @('NOE-P03-KO-U01-UNIT-001','NOE-P03-KO-U02-UNIT-001','NOE-P03-KO-U03-UNIT-001') -Lesson 'Translate historical concept families relation-aware, not as isolated dictionary entries.' -Revisit 'Independent Korean invariant-theory terminology review.'

Add-Record -Category 'terminology' -UnitIds @('U01','U02','U03') -Locators @('lines 3584,3586,3588,3590,3596,3607') -SenseWindow 'Faltung and Defekt plus kogredient/kontragredient transformation behavior.' -FactClasses @($sf,$pref) -Symptom '수축 may attract generic contraction, while 동변/반변 and 결손 must track distinct transformation and parameter senses.' -CauseEvidence @([ordered]@{kind=$pref;detail='Producer used 수축, 수축과정, 수축의 결손, 동변, and a 반변 관계 gloss.';path=$choicesPath;sha256=$choicesSha}) -Attempts @([ordered]@{approach='Translate Faltung as ordinary folding or convolution.';outcome='Rejected.';status='rejected'},[ordered]@{approach='Keep the displayed-process sense and expose alternatives.';outcome='Accepted hold.';status='accepted'}) -Rejected @('Generic folding','Collapse kogredient and kontragredient') -ResolutionState 'held' -Resolution 'Checker must decide this coupled process/representation vocabulary with formula-aware Korean evidence.' -ResidualRisk 'A wrong relation term can invert the transformation claim even with unchanged formulas.' -RecurrenceCues @('Faltung','Defekt','kogredient','kontragredient') -DominanceRisk 'active_qualitative_control' -LexicalBasin 'mixed/contested' -DecisionIds @() -StructuralIds @('NOE-P03-KO-U01-UNIT-001','NOE-P03-KO-U02-UNIT-001','NOE-P03-KO-U03-UNIT-001') -Lesson 'Formula-adjacent relation terms require a shared sense window and independent checking.' -Revisit 'Independent Korean invariant-theory/formula checker.'

Add-Record -Category 'terminology' -UnitIds @('U01') -Locators @('line 3584') -SenseWindow 'Reduzent and Reduktion as historical invariant-theory reducer/reduction terms.' -FactClasses @($sf,$pref) -Symptom 'P03 producer used 환원식, while prior P01 producer metadata used 환원자; neither has Korean evidence.' -CauseEvidence @([ordered]@{kind=$pref;detail='Cross-paper producer conflict is exposed, not normalized.';path=$choicesPath;sha256=$choicesSha}) -Attempts @([ordered]@{approach='Select one cross-paper term by model preference.';outcome='Rejected.';status='rejected'},[ordered]@{approach='Hold both and require corpus-wide reviewer evidence.';outcome='Accepted.';status='accepted'}) -Rejected @('Silent cross-paper normalization') -ResolutionState 'held' -Resolution 'Corpus-wide Korean checker must choose 환원식, 환원자, or an evidenced alternative and log propagation.' -ResidualRisk 'Different terms may falsely imply different historical objects.' -RecurrenceCues @('Reduzent','reducer','reduction of form systems') -DominanceRisk 'active_qualitative_control' -LexicalBasin 'unresolved' -DecisionIds @() -StructuralIds @('NOE-P03-KO-U01-UNIT-001') -Lesson 'Cross-paper inconsistency is adverse evidence, not permission for silent cleanup.' -Revisit 'Corpus-wide Korean terminology decision.'

Add-Record -Category 'terminology' -UnitIds @('U02','U03') -Locators @('lines 3586,3588,3590,3596,3605,3607') -SenseWindow 'Reihe across coordinate rows, symbol rows, variable rows, and series expansion; Unterdeterminante as a minor.' -FactClasses @($sf,$pref) -Symptom '열 can denote row, column, sequence, or family, while the source determinant behavior changes by context.' -CauseEvidence @([ordered]@{kind=$pref;detail='Producer used 변수열, 기호열, and 소행렬식 while separately using 급수전개 for Reihenentwicklung.';path=$choicesPath;sha256=$choicesSha}) -Attempts @([ordered]@{approach='Map every Reihe mechanically to one Korean word.';outcome='Rejected.';status='rejected'},[ordered]@{approach='Keep context-specific terms and expose the polysemy.';outcome='Accepted hold.';status='accepted'}) -Rejected @('Uniform row/column translation without context') -ResolutionState 'held' -Resolution 'Checker must distinguish structural rows/families from analytic series and verify minor terminology.' -ResidualRisk 'Row/column reversal can distort determinant and pairing prose.' -RecurrenceCues @('Reihe','Variablenreihe','Symbolreihe','Reihenentwicklung','Unterdeterminante') -DominanceRisk 'active_qualitative_control' -LexicalBasin 'unresolved' -DecisionIds @() -StructuralIds @('NOE-P03-KO-U02-UNIT-001','NOE-P03-KO-U03-UNIT-001') -Lesson 'Repeated source forms can require multiple target senses; index each occurrence before normalization.' -Revisit 'Independent Korean linear-algebra/invariant-theory checker.'

Add-Record -Category 'terminology' -UnitIds @('U02','U03') -Locators @('lines 3588,3590,3596,3605') -SenseWindow 'Matrizenprodukt, Determinantenaggregat, and corresponding matrices under the source footnote definition.' -FactClasses @($sf,$pref) -Symptom '행렬곱 strongly attracts ordinary matrix multiplication, but the source defines a sum of products of corresponding determinants.' -CauseEvidence @([ordered]@{kind=$sf;detail='The source footnote at line 3590 defines Matrizenprodukt through corresponding determinant products.';path=$authorityPath;sha256=$authoritySha},[ordered]@{kind=$pref;detail='Producer used 행렬곱, 행렬식 결합식, and 대응 행렬.';path=$choicesPath;sha256=$choicesSha}) -Attempts @([ordered]@{approach='Assume modern matrix multiplication.';outcome='Rejected by the recorded source sense window.';status='rejected'},[ordered]@{approach='Retain 행렬곱 provisionally with an explicit checker warning.';outcome='Accepted hold.';status='accepted'}) -Rejected @('Unqualified modern matrix-product reading') -ResolutionState 'held' -Resolution 'Checker must approve an evidenced historical term or add a stable gloss without altering formulas.' -ResidualRisk 'Readers may assign the wrong operation throughout the proof.' -RecurrenceCues @('Matrizenprodukt','corresponding determinants','Determinantenaggregat') -DominanceRisk 'active_qualitative_control' -LexicalBasin 'mixed/contested' -DecisionIds @() -StructuralIds @('NOE-P03-KO-U02-UNIT-001','NOE-P03-KO-U03-UNIT-001') -Lesson 'A familiar modern term is dangerous when the source supplies a non-default definition.' -Revisit 'Independent Korean historical invariant-theory checker.'

Add-Record -Category 'terminology' -UnitIds @('U03') -Locators @('lines 3596,3605,3607') -SenseWindow 'unzerlegbare Identitäten, Zerlegungsidentität, Elementarkovarianten, and Normalformen in the proof.' -FactClasses @($sf,$pref) -Symptom '비분해, 분해항등식, 기본 공변식, and 정규형식 can import modern meanings that differ from the source-defined proof roles.' -CauseEvidence @([ordered]@{kind=$pref;detail='Producer choices are explicitly held and include live alternatives such as 기약, 분해불능, 초등 공변식, and other normal-form terminology.';path=$choicesPath;sha256=$choicesSha}) -Attempts @([ordered]@{approach='Treat modern textbook terms as automatically equivalent.';outcome='Rejected.';status='rejected'},[ordered]@{approach='Keep source-defined sense windows and require proof-level review.';outcome='Accepted hold.';status='accepted'}) -Rejected @('Modern-term substitution without historical evidence') -ResolutionState 'held' -Resolution 'Checker must review this vocabulary as one proof chain and propagate any change through U03.' -ResidualRisk 'A plausible term can misstate atomicity, decomposition, or annihilation conditions.' -RecurrenceCues @('unzerlegbar','Zerlegungsidentität','Elementarkovarianten','Normalformen') -DominanceRisk 'active_qualitative_control' -LexicalBasin 'mixed/contested' -DecisionIds @() -StructuralIds @('NOE-P03-KO-U03-UNIT-001') -Lesson 'Source definitions outrank modern lexical familiarity in historical mathematics.' -Revisit 'Independent Korean proof and terminology checker.'

Add-Record -Category 'historical_register_and_citation' -UnitIds @('U01','U02','U03') -Locators @('lines 3574,3584,3588,3590,3596,3605,3607') -SenseWindow '1909/1910 lecture register, long German sentences, original-language titles, citations, and formula-adjacent prose.' -FactClasses @($sf,$pref) -Symptom 'Literal clause order can be unreadable in Korean, while aggressive rewriting can alter mathematical scope or citation attachment.' -CauseEvidence @([ordered]@{kind=$pref;detail='Producer retained source-language bibliographic titles and drafted long Korean sentences without independent syntactic review.';path=$choicesPath;sha256=$choicesSha}) -Attempts @([ordered]@{approach='Modernize freely and detach clauses from source structure.';outcome='Rejected.';status='rejected'},[ordered]@{approach='Preserve claim/citation order and expose syntax for checker revision.';outcome='Accepted provisional approach.';status='accepted'}) -Rejected @('Unlogged modernization','Translated bibliographic titles presented as originals') -ResolutionState 'held' -Resolution 'Checker must review register, sentence scope, footnote attachment, titles, names, and formula transitions unit by unit.' -ResidualRisk 'Syntactic smoothing can change quantifier, contrast, or proof dependence.' -RecurrenceCues @('long sentence','embedded citation','formula transition','historical title') -DominanceRisk 'active_qualitative_control' -LexicalBasin 'mixed/contested' -DecisionIds @() -StructuralIds @('NOE-P03-KO-U01-UNIT-001','NOE-P03-KO-U02-UNIT-001','NOE-P03-KO-U03-UNIT-001') -Lesson 'Historical register can be modernized only with explicit clause-level source anchors and checker ownership.' -Revisit 'Independent Korean checker returns unit-level syntax and citation decisions.'

Add-Record -Category 'tooling_failure' -UnitIds @() -Locators @('initializer patch construction before any file write') -SenseWindow 'JavaScript template interpolation versus literal PowerShell variable syntax.' -FactClasses @($sf,$comp) -Symptom 'The first initializer apply_patch construction failed with ReferenceError: unit is not defined before the patch tool ran.' -CauseEvidence @([ordered]@{kind=$sf;detail='A JavaScript raw template interpreted a braced PowerShell variable expression as JavaScript interpolation.';path=$null;sha256=$null},[ordered]@{kind=$comp;detail='No initializer, JSONL, CSV, target, or other artifact was written by the failed call.';path=$null;sha256=$null}) -Attempts @([ordered]@{approach='Embed the braced PowerShell variable expression directly in a JavaScript template.';outcome='Failed before apply_patch.';status='failed'},[ordered]@{approach='Use a PowerShell subexpression form that is literal to JavaScript.';outcome='Accepted for the second patch.';status='accepted'}) -Rejected @('Silently omit the failed construction') -ResolutionState 'resolved' -Resolution 'Initializer source now uses a non-interpolating PowerShell subexpression and preserves this failure as HARD-011.' -ResidualRisk 'Mixed-language generators can consume or reinterpret each other’s interpolation syntax.' -RecurrenceCues @('JavaScript template containing PowerShell variable','nested interpolation syntax') -DominanceRisk 'not_applicable' -LexicalBasin 'not_applicable' -DecisionIds @() -StructuralIds @('NOE-P03-KO-WORK-001') -Lesson 'When one language generates another, treat interpolation markers as evidence-bearing syntax and test before writing.' -Revisit 'Recur if a future generated script embeds another language’s braced interpolation in JavaScript.'

[IO.File]::WriteAllLines($jsonlPath,$lines,[Text.UTF8Encoding]::new($false))
$csvText=@($csvRows|ConvertTo-Csv -NoTypeInformation)
[IO.File]::WriteAllLines($csvPath,$csvText,[Text.UTF8Encoding]::new($false))
[pscustomobject]@{record_count=$lines.Count;latest_record_id=('CJK-KO-P03-HARD-{0:D3}' -f $script:sequence);chain_head_sha256=$script:previous;jsonl_path=$jsonlPath;csv_path=$csvPath}|ConvertTo-Json
